### ISSUE TITLE
Sort lineup by number of complaints

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#10]
Suggestion by one of our lawyers: we could use the Citizen's police data project to sort the returned lineup by number of complaints. Those officers that have a history of misconduct are likely to reoffend and we might make it easier for people to find the offending officers by putting them at the top. This approach is similar to search engines putting the most popular sites near the top of the search results list.

**Comment by freddymartinez9** [comment]
I'm torn between rejecting the issue and wondering if we should implement it. 

- officers with high complaint numbers will also have high number of misconduct allegations and our service should address that. 

- bias. This is actually a problem with police lineups (we aren't doing a line up here but its tagentially relevant), so perhaps we should always return _non-identified_ officers with any query. There are people who are introduced into police lineups who are non-suspects (called "fillers") so we may think about doing this. 

Looking at these two, I actually think we should consult a UI/UX person. (FWIW: my recommendation would be to always randomize the results of any query)

**Comment by redshiftzero** [comment]
Given the bias issue noted by @jujueyeball I'm going to close this issue. Instead we should just link to the officer's page on the Citizens Police Data Project (#26).
