### ISSUE TITLE
Staging server

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#104]
Before we cut the next release, we should test the release candidate on a staging server. There's been some big (and good!) changes and we don't have many tests yet, so we'll need to do a bit of manual testing before deploying in production.

**Comment by freddymartinez9** [comment]
- [x] Stand up staging server in AWS free tier 
- [ ] deploy `develop` branch 
- [ ] create staging database to connect to
- [ ] test connectivity to staging db from develop branch

**Comment by freddymartinez9** [comment]
WIP on 162.243.156.49 that the LPL DevOps team should have access to.

**Comment by redshiftzero** [comment]
Thanks for setting this up @freddymartinez9!

**Comment by freddymartinez9** [comment]
https://staging.openoversight.lucyparsonslabs.com is ready.
