### ISSUE TITLE
Officers with multiple photographs

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#105]
At this point we have no more than one photograph per officer in the database. However, we now have sufficient submissions that we _could_ fold in multiple photographs for each officer. Before we do this, we should make sure our gallery query will only return one photograph for each officer (which one?) to display in the main view. We should also have some way of displaying the officer's other photographs as it may aid in identification.

**Comment by scuerda** [comment]
@redshiftzero in my pagination PR I set the query to grab the first returned face from the join. I would assume that internally it would grab the face w/ the lowest ID, which isn’t necessarily the correct behavior. 

One approach would be to track the number of times someone uses a particular face when filing a complaint. Another approach would be to expose some sort of voting mechanism for registered users and let folks determine which photo they believe is most useful. A third approach would be to add a field to the officer model that would allow for an administrator to flag the desired photo. Or maybe all 3 with some sort of hierarchy.

Regarding the mechanism for seeing additional photos, it would be relatively easy to implement a slideshow mechanism within the gallery. Alternatively, an officer detail page (which could contain additional information such as maps of known patrols areas if/when that becomes available and reliable.

**Comment by redshiftzero** [comment]
These are all great ideas - I think having a gallery of the other photos of a particular officer might be good for putting on the `/complaint` route in the short term. 

Longer term, I like your idea of having registered users - perhaps with some reputation measure based on their photo uploads and tagging activity - that enables them to upvote particularly clear/useful images. This seems like a good way of getting the best ranking in a crowdsourced manner. We want to avoid admins/mods having to go in and do any manual work as much as possible since the load on admins is already out of hand (e.g. we already have way more pictures now than what is uploaded in the database because admins are a blocker to verifying tags and getting them inserted into the backend).

**Comment by abandoned-prototype** [comment]
This issue was fixed by the introduction of the "featured" tag
