### ISSUE TITLE
Change "Contribute Work" to Get Involved

### ISSUE THREAD

**Issue by freddymartinez9** [lucyparsons/OpenOversight#117]
Per UX feedback.

**Comment by freddymartinez9** [comment]
I pushed a branch with these commits https://github.com/lucyparsons/OpenOversight/commit/d16095b3d5b3ade8fab01873c796c49865319691 but I have some questions. For reference here is how it looked before: 
<img width="528" alt="screen shot 2016-11-15 at 10 23 03" src="https://cloud.githubusercontent.com/assets/3100220/20313833/c121790c-ab1d-11e6-97c7-18d212613eb3.png">
I did a rename here `+<h1>Contribute Images or Get Involved</h1>`  but I'm wondering what people think about renaming the button. I personally think its _just okay_ as is, but it maybe could be a more explicit `Get Involved!`

**Comment by redshiftzero** [comment]
I think what you have in your branch looks good - feel free to submit that PR :+1:

**Comment by redshiftzero** [comment]
Implemented in #119
