### ISSUE TITLE
Schedule weekly backups for our data

### ISSUE THREAD

**Issue by b-meson** [lucyparsons/OpenOversight#118]
related to #38

**Comment by redshiftzero** [comment]
Note that we need to backup both the database (which we can do with e.g. `pg_dump`) as well as the images on S3 and Google Drive... we should automate this as much as possible

**Comment by freddymartinez9** [comment]
started working on this in a branch https://github.com/lucyparsons/OpenOversight/tree/fabricbackup but its still not complete...I'll continue working on this.

**Comment by freddymartinez9** [comment]
opened #181 for doing this in `fab`. we might need to schedule a cron to run on a light weight computer like a Pi... and then use onionshare to broadcast the backup for censorship resistance.

**Comment by freddymartinez9** [comment]
ran into an issue with doing this task, will be debugging further. 
```
  File "/Library/Python/2.7/site-packages/fabric/utils.py", line 213, in __getattr__
    raise AttributeError(key)
AttributeError: unprivileged_user
```

**Comment by r4v5** [comment]
Running what syntax? You do need to specify an environment or it'll not have that key populated.

**Comment by freddymartinez9** [comment]
@r4v5 I'm not a smart man and was running the `fab` commands in reverse order (which I documented specifically because I was doing this so often...).

**Comment by freddymartinez9** [comment]
Okay I have configured the nginx user to use AWS CLI. Here is a one line backup we can add to the `fab` file and it should allow us to backup s3 to our local machines. 
`aws s3 sync s3://openoversight-staging /home/nginx/openoversight_backup/s3/openoversight-staging/`
Right now it takes it from S3 and backups to the application server, which is a bit brittle.

**Comment by redshiftzero** [comment]
This is getting moved to 0.2.1 - but it's really important. We'll have to manually be backing stuff up until this gets worked out.

**Comment by redshiftzero** [comment]
Great steps towards this in #243. @r4v5 noted that given how much data we have in S3 at this point, we are going to be paying through the nose if we do this backup every week. So we should build on #243 to enable incremental backups.
