### ISSUE TITLE
Tagging feature

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#13]
We want an application that displays submitted images that have not been tagged yet, which one can grab by `select * from officers.raw_images where is_tagged = 'f'`. 

Then this application would allow people to click on a face and drag a box to select the cutout of the face - this is what will be stored in `face_position` in table `faces` and displayed in the digital lineup. Then next to each face, there should be two fields: one for name and one for badge number which the user should fill in one or both of. The user should be able to tag a single image multiple times.

Upon submission of the form, if there is one officer that matches the name or badge number then we add a row in table `faces` linking the `officer_id` with the `img_id` at `face_position`. If there is more than one officer (e.g. in the case of a surname that is very common or a badge number that has been reused) or if there are zero officers (e.g. in the case of a new officer that does not appear in our roster yet) we will need to manually review it.

**Comment by scuerda** [comment]
How about using OpenCV to auto detect faces / filter out images that need manual face clipping?

**Comment by scuerda** [comment]
Oops. Scratch my question...just saw #6 re: OpenFace.

**Comment by redshiftzero** [comment]
But yes that would be great! I believe @JoshuaOpolko gave this a shot and found that a lot of faces were not being picked up, so it might require a bit of optimizing to make sure we don't throw away good data.

**Comment by scuerda** [comment]
What jumps to mind is something akin to the OpenStreetMap iD editor. Pre-select what can be and then expose a task mgmt system for letting folks handle the manual parts. Is that what what you were thinking of as well?

**Comment by redshiftzero** [comment]
It looks like that would be great for the map input. 

Also, I think the minimal version of this photo tagging feature will probably not have face detection but until then we could use something like this JQuery plugin for users to select the locations of faces: http://odyniec.net/projects/imgareaselect/

**Comment by scuerda** [comment]
Re: auto face detection, is the full Chicago image set available anywhere for people to try out different approaches?

**Comment by JoshuaOpolko** [comment]
@scuerda @redshiftzero  the pics downloaded so far are in cpd_pictures. Please let me know if there are any issues accessing them. git clone should retrieve them all.  Otherwise maybe we can put some or all somewhere more optimized for photo collections.

**Comment by scuerda** [comment]
@JoshuaOpolko hmmm, I can't seem to find that directory. Can you link to it?

**Comment by freddymartinez9** [comment]
@scuerda added you to the cpd_images repository.

**Comment by JoshuaOpolko** [comment]
It is at https://github.com/lucyparsons/cpd_pictures 
If there's another service like google drive or similar that might be easier I can upload them there too.  I just want to avoid splitting/recombining sets too much but for ease of use the photos can go just about anywhere.

**Comment by redshiftzero** [comment]
WIP:

![tagging](https://cloud.githubusercontent.com/assets/7832803/21840117/8bca39ca-d790-11e6-85d4-9503d94b6a27.gif)
