### ISSUE TITLE
Use celery tasks for sending emails

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#146]
Right now we're using threads to send emails (in PR #145 to confirm user accounts and do password resets), but the application might scale a bit better if we use a[ task queue ](http://decafbad.com/blog/2008/07/04/queue-everything-and-delight-everyone/)(e.g. Celery) for this.

**Comment by freddymartinez9** [comment]
I'm not suggesting that we need another mail server (I can hear @r4v5 screaming right now) but Celery does seem to have good AWS SQS support (we can even pull it from the IAM, so no need to deal with the `.env` for grabbing credentials)

**Comment by r4v5** [comment]
If it's just dispatching emails, SQS seems overkill for a service running on one box with signups at such a low rate. Locally persisted queue with a handful of consumers (where the number of consumers that fits into a hand is roughly 2, but configurable in an environment-dependent way) would be better I think until we reach a point of needing that scale. It also makes swapping out that architecture for service continuity reasons easier.
If queues are local to the machine, that also prevents issues that may arise from cross-environment contamination ("whoops, my laptop was listening to the production queue and a few folks didn't get emails!" is a bad place to be, he says, having literally done that before).
We'll also need some queue consumer / queue depth monitoring, which I'd _love_ to have be abstracted away to a single endpoint I can make our existing monitoring service hit and get a basic pass/fail health check on.
Do we want any way for the success or failure of those tasks to be communicated back to the end user's browser? I'm leery of that being used to enumerate valid accounts based on time to return.
(Is this realistic/part of our threat model? Are we currently vulnerable to it?)
