### ISSUE TITLE
Blank Submissions

### ISSUE THREAD

**Issue by foebrian** [lucyparsons/OpenOversight#175]
When on an OO submission page just entering a name and clicking submit with no image file selected appears to return a result of "File uploaded successfully https://...." 

No error or marker for review of submission is presented after submit button pressed when no image file is selected.

**Comment by redshiftzero** [comment]
Thanks for pointing this out @foebrian!! We'll be dumping the Google form in our next release (0.2) in favor of the image upload functionality recently merged in PR #149 so I'm going to close this one.
