### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by teonbrooks** [lucyparsons/OpenOversight#183]
Hey @redshiftzero. Here's a resource for data quality using crowdsourcing techniques:

http://gureckislab.org/mtworkshop/

I will add any other resources that I might found

**Comment by redshiftzero** [comment]
Awesome thanks @teonbrooks!

**Comment by redshiftzero** [comment]
Added this resource to the [OpenOversight wiki](https://github.com/lucyparsons/OpenOversight/wiki) so closing this. Thanks again!
