### ISSUE TITLE
Log certain things like exceptions/errors so we have visibility into the app

### ISSUE THREAD

**Issue by r4v5** [lucyparsons/OpenOversight#186]
Certain things, especially things that cause exceptions or errors have no logging around them to surface that to admins and they should.
Example:
https://github.com/lucyparsons/OpenOversight/blob/develop/OpenOversight/app/main/views.py#L297
"Uploading a file failed." Why? Was it incorrect S3 permissions? Something else? We should log the original exception instead of swallowing it.
Another example:
Creating an admin user should log _something_.

**Comment by redshiftzero** [comment]
This was completed in #189, so closing!
