### ISSUE TITLE
Allow larger nginx request sizes

### ISSUE THREAD

**Issue by r4v5** [lucyparsons/OpenOversight#190]
Uploading a 2MB file fails on the nginx side with a 413 Request Body Too Large. We should figure out the max size we're willing to allow, and configure nginx to allow it.

**Comment by freddymartinez9** [comment]
worth testing up to 20MB, I think this might work. 

```
server {
        [snip]
        root /var/www/html;
        access_log off;
        error_log /dev/null crit;
        location / {
                # Gunicorn proxy pass rule
                proxy_pass http://127.0.0.1:4000;
                proxy_redirect     off;
                client_max_body_size 20M;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_connect_timeout 300s;
                proxy_read_timeout 300s;
        }
```

**Comment by freddymartinez9** [comment]
actually I do notice we also set this: `MAX_CONTENT_LENGTH = 16 * 1024 * 1024`

**Comment by r4v5** [comment]
Then yeah, let's set it to 20 on the nginx side so we don't have users seeing an ugly unstyled nginx page until they exceed it.

**Comment by redshiftzero** [comment]
Was this fixed? If so is [this](https://github.com/lucyparsons/OpenOversight/blob/develop/DEPLOY.md) the only place we need to update in the repo before closing?

**Comment by r4v5** [comment]
Dunno if it made it to prod.

**Comment by r4v5** [comment]
It's now in place in prod; added it to the repo docs in #206.
