### ISSUE TITLE
Multi-city scaling

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#216]
Longer term, we need to scale this to multiple cities. I was thinking about spinning up a new webserver/database server for each agency, but 1) that doesn't scale very well cost wise and 2) it would be useful to have a centralized set of users so that moderation and volunteering can be managed centrally.  

To modify OpenOversight to support multiple departments we should:
- [x] Extend schema to include a table for mapping police department names to department_id
- [x] Extend all models to include a department_id field (is this the right database design? 🤔 )
- [x] Use department_id in the find an officer form
- [x] Add a button on the frontpage for the department that quicklinks to the find an officer form with the right department selected
- [x] Image submission form should have a department selection
- [x] Image, tag, officer pages all should show which department the officer was from
- [x] Volunteers should select which department they want to work on. There should also be a volunteer dashboard showing e.g. "500 images in CPD need classifying"

We might also create routes like `/chicago` `/nypd` that redirect to the find an officer form with the correct city filled out. 

I can make individual issues for these things as we approach them, for now I am just brainstorming. Imho each of these things is not really that complicated, and this should be done in a minor release soon. 

See: #295 #296 #297 #298

**Comment by elimisteve** [comment]
I think working on this would count as civic hacking for SF, don't you?

**Comment by redshiftzero** [comment]
The SFPD and Oakland PD data is ripe for the FOIAing

**Comment by elimisteve** [comment]
Sounds awesome

**Comment by jujueyeball** [comment]
this strikes me re a side project, which would be tracking problem officers who have shuffled from dept to dept to dept rather than facing discipline

**Comment by redshiftzero** [comment]
This is completed and in production
