### ISSUE TITLE
Design/UI improvements for classification volunteer app

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#234]
I would love some design/UI/UX feedback for the classification volunteer app, which currently looks like this:

![screen shot 2017-04-09 at 11 55 38 am](https://cloud.githubusercontent.com/assets/7832803/24840081/7879a312-1d1b-11e7-8af4-d694886b4e0f.png)

I was thinking that a better design would have the image centered, with much simpler buttons with icons instead of so much text. Maybe simplify the question to "Are there police in the image?", and then three buttons horizontally over the image, with a check, a crossed-out, and "Skip"?

**Comment by geminiimatt** [comment]
User Story:
"As a user I should be able to automate sorting of images by using phone swipes or keyboard keys."

Description:
The UX/UI will change based on device.
For laptops it will be keyboard linked.
For mobile phones it will be swipe based. 
This will increase speed of entry submission. 
There should be a JS confirm before the next image comes in.

**Comment by redshiftzero** [comment]
Made some changes, it looks like this now:

![8dd8b76a-1e4d-11e7-83cd-2debddab823b](https://cloud.githubusercontent.com/assets/7832803/24943571/14820fdc-1f0c-11e7-8c16-30a170cd7f47.png)

**Comment by redshiftzero** [comment]
This is looking pretty good now, we have the keyboard shortcuts too thanks to a contributor, so I'm gonna close this. Let's open more specific followups as needed
