### ISSUE TITLE
Make officer face cutouts a uniform, responsive size

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#236]
We started displaying just the cutout of the face in officer search results. However there is a wide range of sizes in the cutouts. We make the cutouts using a little CSS (Jinja templating is in here too):

```
background-image: url({{ officer_image }});
background-repeat: no-repeat;
background-position: -{{ officer.face.first().face_position_x }}px -{{ officer.face.first().face_position_y }}px;
width: {{ officer.face.first().face_width }}px;
height: {{ officer.face.first().face_height }}px;
```

We need these to be a uniform, responsive size. Suggestions?

**Comment by redshiftzero** [comment]
This is blocking #278, because one of the first images that comes up is a really massive one:

<img width="809" alt="screen shot 2017-06-19 at 12 53 46 pm" src="https://user-images.githubusercontent.com/7832803/27296329-6b331b9c-54ee-11e7-86a7-f3cffb91afb5.png">

**Comment by raq929** [comment]
To clarify: We're not trying to change the way the cutouts are created, just the way they are displayed, right?

**Comment by redshiftzero** [comment]
Ah and once this is implemented, we should use it also on the officer profile, as right now we're including the entire photo (not just the cutout)

**Comment by raq929** [comment]
I've been playing around with this for a while, basically trying to do what cropper.js does with image previews, and I'll push a relevant branch, `236-consistent-photo-size`. However, at this point, I think the right solution is to actually crop the image at the time of tagging and save that as the face. I don't think it will be that hard to implement, and it'll save a lot of hassle when it comes to displaying the image and having it be responsive.
