### ISSUE TITLE
Add HTML formatting and linting to `pre-commit`

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#239]
Once we find a good linter for HTML, we should add it to CI. 

I was using [bootlint](https://github.com/twbs/bootlint) and [html-linter](https://pypi.python.org/pypi/html-linter/) using the `--disable=optional_tag,protocol` options to clean up some of the HTML in #238.

If there's something better out there please comment and let us know! ✨

**Comment by jrabbit** [comment]
https://github.com/motet-a/jinjalint exists but doesn't seem too robust

**Comment by abandoned-prototype** [comment]
Now that we use pre-commit adding an html template linter should be relatively easy and pretty helpful

**Comment by michplunkett** [comment]
It doesn't look like jinjalint is being mainted, but djlint is: https://www.djlint.com/docs/languages/jinja/

We could likely implement this pretty easily.

**Comment by michplunkett** [comment]
This is gonna be split up into two PRs, one formatting and one for linting. Since the changes to the HTML, JS, and CSS will be so vast for just the formatting, no reviewer will actually be able to see the code that is changed for formatting as opposed to linting.

**Comment by michplunkett** [comment]
The HTML formatting part is done, but the linting is not.
