### ISSUE TITLE
incorrect permissions on /tmp/openoversight.log

### ISSUE THREAD

**Issue by monofuel** [lucyparsons/OpenOversight#255]
after running `vagrant up`, the server is not running. looking at the gunicorn logs `/var/log/gunicorn/oo.log` it shows a permission denied error.

error in logs:
```
IOError: [Errno 13] Permission denied: '/tmp/openoversight.log'es/gunicorn/util.py", line 353, in import_app
```

permissions for new vm:

```
root@vagrant-ubuntu-trusty-64:/var/log# ls -la /tmp
total 24
drwxrwxrwt  5 root    root    4096 May  7 00:05 .
drwxr-xr-x 23 root    root    4096 May  7 00:01 ..
drwxrwxrwt  2 root    root    4096 May  7 00:01 .ICE-unix
-rw-------  1 vagrant vagrant  396 May  7 00:04 openoversight.log
drwxrwxrwx  4 root    root    4096 May  7 00:01 vagrant-puppet
drwxrwxrwt  2 root    root    4096 May  7 00:01 .X11-unix
```

the service is ran under the user www-data

**Comment by freddymartinez9** [comment]
Great point @monofuel. Adding @r4v5 for review

**Comment by freddymartinez9** [comment]
```
grep -iRI --color "tmp/o" * 
OpenOversight/OpenOversight/app/__init__.py:    file_handler = RotatingFileHandler('/tmp/openoversight.log', 'a',
``` 
so we should use Puppet to override this file owner to `$system_user`.

**Comment by freddymartinez9** [comment]
@monofuel @r4v5 I pushed a commit https://github.com/lucyparsons/OpenOversight/commit/48ce39e6cd2b53fd8a0c3d0db2fb6f9edd7279ee here that works for me. however, it doesn't use the `www-data` on the user but uses `$system_user`. Can we get a test on this branch?
