### ISSUE TITLE
autoenv misconfigured(?)

### ISSUE THREAD

**Issue by elimisteve** [lucyparsons/OpenOversight#257]
```
$ cd repos/OpenOversight/OpenOversight/
autoenv:
autoenv: WARNING:
autoenv: This is the first time you are about to source /home/steve/repos/OpenOversight/OpenOversight/.env:
autoenv:
autoenv:     --- (begin contents) ---------------------------------------
autoenv:     # this file is managed by puppet
autoenv:     [global]
autoenv:     SECRET_KEY = terriblecsrftoken
autoenv:     SQLALCHEMY_DATABASE_URI = postgresql://openoversight:terriblepassword@localhost/openoversight-dev
autoenv:     
autoenv:
autoenv:     --- (end contents) -----------------------------------------
autoenv:
autoenv: Are you sure you want to allow this? (y/N) y 
[global]: command not found
SECRET_KEY: command not found
SQLALCHEMY_DATABASE_URI: command not found
```

**Comment by elimisteve** [comment]
I don't know if this is an issue with my machine or a misconfig in `OpenOversight/OpenOversight/.env`

**Comment by r4v5** [comment]
To be honest, this one's a bit low priority, but will probably be tackled as part of some provisioning rework I have planned. The .env file is only really there to be read by the dotenv code in the app, and we provide a Vagrantfile so the app's dependencies don't even have to touch your machine (outside of vagrant, I mean).
I know those aren't syntactically-valid assignments in bash and therefore are slightly outside the spirit of a .env, but dotenv can read 'em just fine.
I'd suggest just answering 'no' to autoenv there. and using vagrant for local development, unless that doesn't work for you.

**Comment by abandoned-prototype** [comment]
If I understand this correctly, the `.env` file was created as part of the vagrant deploy. We deprecated/removed the use of vagrant in https://github.com/lucyparsons/OpenOversight/pull/549, so I am pretty sure this issue is resolved as a result.
