### ISSUE TITLE
Password reset emails not being sent

### ISSUE THREAD

**Issue by elimisteve** [lucyparsons/OpenOversight#258]
Can't tell whether this is an issue with the code, a server misconfiguration, OpenOversight's mail sending service (Sendgrid/Mailgun/etc), or something else... but I do know that I didn't receive a password reset email from production :-).

**Comment by r4v5** [comment]
Oof, this one's on me. The proper credentials should be there now.

**Comment by redshiftzero** [comment]
Thanks for reporting this @elimisteve! And for fixing so fast @r4v5! :heart: Note I just SSHed into prod and sent out the emails for the unconfirmed users, so we should be good now.

For reference this is how I sent those emails from the from the Flask console (which one can start with `manage.py shell`):

```
from app.email import send_email
from app.models import User
unconfirmed_users = User.query.filter_by(confirmed=False)
for user in unconfirmed_users:
    token = user.generate_confirmation_token()
    send_email(user.email, 'Confirm Your Account', 'auth/email/confirm', user=user, token=token)
```
