### ISSUE TITLE
Link to Citizen Police Data Project 

### ISSUE THREAD

**Issue by b-meson** [lucyparsons/OpenOversight#26]
Consider making a way to link directly to Invisible Institute's database of office complaints. Similar to issue #10

**Comment by freddymartinez9** [comment]
[API in staging environment](http://staging.cpdp.co/api/v1/suggestion/?text=%3Csomething%3E ) and [documentation](http://docs.cpdp.apiary.io/#reference/0/suggestion/get-suggestion) for their upcoming API.

**Comment by freddymartinez9** [comment]
FWIW, you have to use the staging environment similar to `curl http://staging.cpdp.co/api/v1/suggestion/?text=Logan` and what we need is the returned URL https://cpdb.co/officer/logan-westcott/7989. We can, of course, query based on badge numbers which may be a better approach 
```
curl http://staging.cpdp.co/api/v1/suggestion/?text=6585

{"UNIT":[],"OFFICER":[{"text":"6585","score":2.0,"payload":{"url":"https://cpdb.co/officer/alexus-logan/4264","result_text":"Alexus Logan","result_extra_information":"Badge 6585"}}],"NEIGHBORHOODS":
```

**Comment by freddymartinez9** [comment]
A very [basic](https://gist.github.com/freddymartinez9/869fbf6a32edbb4029f2e13f60f11c15) bit of code that works using II's staging API. I'm not sure the best way forward. We probably don't want the webpage to make 40+ calls (one per officer for every search) being sent to II. Then again, we don't want to maintain our own clone of the Invisible Institute's data. Speaking very briefly with some of them, they are open to discussing their API model as its still being developed...

**Comment by freddymartinez9** [comment]
I made a very basic change to the `gallery.html` [here](https://github.com/lucyparsons/OpenOversight/commit/f1e0f739a6b47ee5db8a365c17b2ac094be4a4ea) but I'm not sure this is the proper way to do it because I'm not sure how python and html work together in our webapp. I also tried to use `requests` because its so much nicer than `urllib2`

**Comment by redshiftzero** [comment]
FYI @freddymartinez9 it's probably better to put this complaint information in the officer profile only and put the API call in the view function

**Comment by redshiftzero** [comment]
Just a note: this suggestion endpoint appears to be ignoring `text` and returning a random officer with first name John.

**Comment by redshiftzero** [comment]
Looking at the API documentation, I'm not sure it gives us what we want. We want to be able to specify a badge number and last name and get the URL of the officer's profile in II's database. Ideally it would also give us the number of complaints the officer has and how many complaints resulted in disciplinary action so we could display that on the officer profile.

**Comment by redshiftzero** [comment]
We want to use whatever powers this: https://twitter.com/CPDPbot (pretty cool bot!)

**Comment by redshiftzero** [comment]
Given 1) this is non-essential for the volunteer improvements in 0.2 and 2) it doesn't look straightforward to just use the API as it appears to be functioning, I'm going to move this ticket onto the next major release milestone (but if someone wants to work on this and implement it before then I will merrily merge).

**Comment by redshiftzero** [comment]
(note I think their API has changed significantly since I last looked so this is worth another investigation)

**Comment by abandoned-prototype** [comment]
Will assign this to myself since it looks like I already started some of that work. Definitely possible to have our CPD officer profiles have a link their cpdp counterparts. I will also investigate feasibility of directly incorporating cpdp data onto the profile

**Comment by abandoned-prototype** [comment]
Some of this was actually done. Chicago cop profiles in OpenOversight now have links to their cpdp profiles. Will have to update them occasionally.
