### ISSUE TITLE
UI bug: entire leaderboard is on 1 line

### ISSUE THREAD

**Issue by elimisteve** [lucyparsons/OpenOversight#273]
See https://openoversight.lucyparsonslabs.com/leaderboard

**Comment by elimisteve** [comment]
![screenshot-openoversight-uibug-screenshot_2017-05-22_16-58-13](https://cloud.githubusercontent.com/assets/139603/26333092/f1bcf6d2-3f0f-11e7-9469-ca78358de5a1.png)

**Comment by freddymartinez9** [comment]
Thank you for the PR @elimisteve!

**Comment by elimisteve** [comment]
:+1:
