### ISSUE TITLE
batch uploading doesn't allow removing "file type not allowed"

### ISSUE THREAD

**Issue by freddymartinez9** [lucyparsons/OpenOversight#280]
If you want to drag and drop 16 files and one of them is a file type not allowed, you can't remove the one bad image. 

To reproduce this, try batch uploading 16 images but name one .JPG instead of .jpg

**Comment by freddymartinez9** [comment]
same if one image has already been uploaded to OO's S3 bucket.

**Comment by redshiftzero** [comment]
Not an issue, same reason as in #281. Closing!
