### ISSUE TITLE
Images are served with the wrong Content-Type

### ISSUE THREAD

**Issue by bmintz** [lucyparsons/OpenOversight#290]
Images are currently served with `Content-Type: binary/octet-stream` which is fine for `<img>` elements.
However, attempting to view the image via Right-Click -> View image in Firefox for example prompts the user to download the image.

Please serve images with `Content-Type`s corresponding to their filetypes/file magic.

**Comment by r4v5** [comment]
I noticed this too, and this is something we should do. This'll require some S3 magicks on my or @freddymartinez9's end and an update to the documentation in DEPLOY.md. I'll tackle it, but am unlikely to get to it before Friday.
