### ISSUE TITLE
Store department name in database

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#296]
Let's store the name of the police department in `config.py` (if you don't think that's a good place, speak up) so that "Chicago Police Department" is not hardcoded everywhere in the HTML templates

**Comment by r4v5** [comment]
Is this as a stepping stone to multiple PDs in one DB, or in lieu of it, or can they both coexist in a way I'm not seeing?

**Comment by redshiftzero** [comment]
Ideally, this codebase would support both (1) multiple police departments in one database as well as (2) enable this code to be easily forked to be used for independent instances of OpenOversight. I was thinking that `config.py` was the right place to store this, but that works for the 2nd goal but not the first, so I've changed this issue to be storing the name of the department in the database. We should move all department-specific data into the database (i.e. name of department, rank levels, possibly more).

**Comment by redshiftzero** [comment]
Done in #300, and removing hardcoded "Chicago Police Department" in index template is now an item in followup #308
