### ISSUE TITLE
Generalize schema

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#298]
We need to generalize this schema so that it can work for multiple police departments that:

- [ ] have better assignments data
- [ ] have badge numbers that do and do not change
- [ ] (more here when we come across it in a new police department)

**Comment by r4v5** [comment]
Backend-wise:
I see a table with Departments in it, and then adding a `department_id` column on every other table that has department-specific info with a FK to` department.id`. We should work out what other columns `departments` needs: id (int), name (varchar255), ...other.
We'll also need to either add `department` to a lot of routes, or set it on a cookie and read it back. It's more work for us but I'm fonder of the first option.

**Comment by freddymartinez9** [comment]
I'm generally in favor of less cookies and less web app complexity. Let's put it ina DB schema if it sounds good.

**Comment by redshiftzero** [comment]
closing this, let's file more specific issues for particular data issues as they arise
