### ISSUE TITLE
Enable admin to update department info

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#306]
For example "University of California Police Department" should probably be "University of California Berkeley Police Department", oops. We need an admin route to edit this.

**Comment by redshiftzero** [comment]
Also should probably add a column for `complaint_url` for where the people searching can send complaints.

**Comment by cultureclap** [comment]
I just learned of this project! I am super excited to contribute -- haven't worked with Flask much. Is this saying a route is needed in the views, connecting to a form that will allow for such an edit to be made?

**Comment by b-meson** [comment]
Hi @cultureclap, Welcome!

I know @redshiftzero is our Python flask guru but my understanding is that yes, you would add a new route in main/views.py that had something like...

```
@main.route('/unit/<int:unit>/edit', methods=['GET', 'POST'])
@login_required
@admin_required
def edit_unit():
    form = EditUnitForm(department=first_department)

    if form.validate_on_submit():
        unit = Unit(descrip=form.descrip.data,
                    department_id=form.department.data.id)
        db.session.add(unit)
        db.session.commit()
        flash('Unit {} edited on OpenOversight'.format(unit.descrip))
```
