### ISSUE TITLE
Set `timestamp` columns in the database to `timestamptz`

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#323]
We are currently using naive datetime objects everywhere in this application, but we should be using timezone-aware datetimes in the application (e.g. using `moment.js` or similar) and store them in the database as UTC. We should not assume the timezone of the user. 

From [comment](https://github.com/lucyparsons/OpenOversight/pull/310/files#r149565242) by @r4v5:

> there’s a potential for discrepancy when initializing these with dates (at time 00:00) and being returned referencing the day before/after we intended.

**Comment by r4v5** [comment]
:(

**Comment by redshiftzero** [comment]
---> :)

**Comment by michplunkett** [comment]
I talked to @abandoned-prototype today about this and the idea is to set all times in the DB to UTC. That should allow us localize times correctly in the future.

**Comment by michplunkett** [comment]
Column name changes before updating data types:
- `assignments`: `start_date` -> `started`, `resign_date` -> `resigned`
- `descriptions`: `date_created` -> `created`, `date_updated` -> `updated`
- `notes`: `date_created` -> `created`, `date_updated` -> `updated`
- `raw_images`: `date_image_inserted`: `created`, `date_image_taken`: `taken`

**Comment by michplunkett** [comment]
Done!
