### ISSUE TITLE
Application should prevent users from associating faces with wrong department

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#325]
1. User is identifying images associated with Berkeley Police Department
2. User mistypes OpenOversight ID
3. ID is of a different department
4. App should prevent user from entering the wrong ID by flashing a message ``The officer is not in {{ department.name }}. Are you sure that's the correct OpenOversight ID?``

This also should have a unit test

**Comment by leifan89** [comment]
I'm taking a look at this as my first issue! PR forthcoming 🙂
