### ISSUE TITLE
Officer list view

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#327]
For each department, a volunteer should be able to see a list view with the items known about the officer, number of photos, etc.

**Comment by redshiftzero** [comment]
This is a frequent request from users: 

> It would be cool if the search dealt with wildcards or there was a way just to view the data as a table. The query can create very inconsistent results, sometimes broad searches come back with 0 results, and it would be helpful to be able to just scroll down to the M's and see if anything matches the last name length/first initial (which would really help with blurry photos)

**Comment by raq929** [comment]
@redshiftzero Questions!
Do you want the default pagination to be set via env variable like it is in the gallery? What do you prefer the default to be? I'm using 10 right now, but if departments are VERY large, people might want a bigger number.

What data do you want to display besides the officers name/badge number? (Relatedly, is the number of photos of an officer the number of 'faces'?
Also, I do think it makes sense to display a small photo, as that will make scanning through officers potentially easier. What do you think?

**Comment by redshiftzero** [comment]
> Do you want the default pagination to be set via env variable like it is in the gallery?

Sure I think that makes sense. We can add a new env var for the list view if we don't have it to be the same. For the list view, I do think it would be beneficial to have a larger default pagination - 25-50? - as some departments (e.g. Chicago Police Department) do have a huge number of officers (~15k+). 

> What data do you want to display besides the officers name/badge number? 

In addition to those two, I think the most important to have are:

* Rank
* Race
* Gender
* Number of photos

> (Relatedly, is the number of photos of an officer the number of 'faces'?)

Yep, this is true. 

> Also, I do think it makes sense to display a small photo, as that will make scanning through officers potentially easier. What do you think?

Sounds reasonable to me!

**Comment by raq929** [comment]
Thanks! The only thing I worry about in having the list be large is loading times for photos...
I'll look into ways to make that faster, but if the choice is between removing photos and having a larger default, I think we want to go with larger default, yes?

**Comment by redshiftzero** [comment]
Yep agreed
