### ISSUE TITLE
Add field for officer salary information

### ISSUE THREAD

**Issue by camfassett** [lucyparsons/OpenOversight#334]

**Comment by redshiftzero** [comment]
We should be able to display the salary history of an officer on their profile. Administrators should be able to update this information.

**Comment by dismantl** [comment]
It would be great to include overtime pay as well. And down the line, salary increases could be noted on the officer timeline in #473.

For now, I would propose a `salary` database table with the following items:
* annual salary
* total overtime
* fiscal year
