### ISSUE TITLE
Fix wiggle on hover for item in navigation bar

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#336]
There's a very slight wiggle in the position of items in the navbar when your hover over an item:

![wiggly-navbar](https://user-images.githubusercontent.com/7832803/34322406-25995e18-e7db-11e7-9ee2-728e7e14098d.gif)

**Comment by redshiftzero** [comment]
cc @furfreemi in case you feel like some holiday coding :smile:🎄

**Comment by furfreemi** [comment]
whoooops haha that's definitely my b, i'll get that fixed next pr :)
