### ISSUE TITLE
move to OO.com instead of a subdomain

### ISSUE THREAD

**Issue by b-meson** [lucyparsons/OpenOversight#350]
this should be easy to do if we clone the VM we use and point the DNS to a new IP.
 - note: requires a new LE cert.

**Comment by r4v5** [comment]
http://openoversight.com already redirects to oo.lpl.com; do we want the canonical name to be oo.com instead? that's just changing some nginx rules and updating letsencrypt; the domain already is live. I'd rather have both since we have a substantial amount of collateral with the old address.

**Comment by b-meson** [comment]
The problem is I navigate directly to `oo.com/submit` will throw a scary HTTPS error, and it might be better to just keep it simpler (less words for our volunteer to type).

**Comment by pierwill** [comment]
got the same https error @b-meson

**Comment by r4v5** [comment]
letsencrypt cert now being served up for openoversight.lucyparsonslabs.com, openoversight.com, www.openoversight.com. Logging in to make sure the bucket CORS permissions and whatnot are correct for image display, and then closing this as fixed.

**Comment by r4v5** [comment]
CORS permissions are now correct. Note that we're not doing a canonicalization of hostname (though we can if we want?) so folks are going to see whichever hostname they provided in the URL bar for now.
