### ISSUE TITLE
Scrape BPD for arrest data to fill in officer profiles

### ISSUE THREAD

**Issue by b-meson** [lucyparsons/OpenOversight#351]
We could use a python library to grab arrest data that could better fill in our understanding of BPD.

**Comment by redshiftzero** [comment]
Can you point to the data for this @b-meson?

**Comment by redshiftzero** [comment]
ping - any more detail on this @b-meson?

**Comment by b-meson** [comment]
Their API is on the Berkeley City Open Data portal https://dev.socrata.com/foundry/data.cityofberkeley.info/i5dr-3ir7

**Comment by redshiftzero** [comment]
How can this data be linked to individual officers?

**Comment by redshiftzero** [comment]
Looked at this, the data is only of arrests (and includes the arrestees full name 😬 but not the officer ID or name), so not useful for OpenOversight as is
