### ISSUE TITLE
"Server responded with 0 code" on JPG upload

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#359]
A user saw this today: 

![error](https://user-images.githubusercontent.com/7832803/35493779-c1fcb1b4-046a-11e8-9b41-049e92e3b5f4.png)

The task here is to determine why this is happening (i.e. try to reproduce the issue), and to fix it so it  doesn't happen again, or it at least provides a more useful response to users

**Comment by r4v5** [comment]
At a glance from the file size, this is probably nginx kicking back a useless-to-users 413 or similar error message when the upload happens and the javascript not reporting that properly; I’ll take a look at nginx settings tomorrow and try to straighten it out/find steps to reproduce.

Do we have a suggested max file size in mind, @redshiftzero?

**Comment by redshiftzero** [comment]
Ahh, good call @r4v5. Since this is just for photos, maybe 50 MB to be on the safe side?

**Comment by r4v5** [comment]
Bumped to 50MB; anyone have a high res picture they want to test with?

**Comment by redshiftzero** [comment]
Ah... right - we also need to change `MAX_CONTENT_LENGTH` in `config.py` - PR incoming
