### ISSUE TITLE
Dev Environment

### ISSUE THREAD

**Issue by r4v5** [lucyparsons/OpenOversight#36]
If we want to develop with any amount of rigor, we should have a dev environment. This is probably (because I'm doing it, and I stick with the devils I know) going to be a vagrant box provisioned via puppet, with a helluva lot of rake magic. I'm also going to try to make this match the production schema with dummy values, but an actual migrations management system is also work we should do (in a separate issue).

**Comment by scuerda** [comment]
Not sure what the status of this issue is, but I have plenty of experience working with both ansible/vagrant and docker within a similar stack. I have less experience with Puppet, but would be happy to chip away at this in any of the above.

**Comment by r4v5** [comment]
Hi @scuerda! Thanks for the offer to help.
I have the code and doc changes for this done as part of #87; if you could run through it and see if you get a working dev environment after checking out that branch and following the instructions, that'd be super helpful. Any ambiguities or friction you run into would be helpful to know about.

Also, if you have docker knowledge, rebasing #50's branch off of #87 and updating the docker work to work accordingly would help the folks who want to use docker instead.

**Comment by freddymartinez9** [comment]
@scuerda Thanks for the offer! I did a quick sanity check on #87 so if you want to look at that and make your own feedback, that would also be helpful. I didn't approve the PR because Im not as good with the development environments as others are.

**Comment by scuerda** [comment]
@r4v5 @freddymartinez9 sounds like a plan! I need to spin up a dev environment so that I can take a look at a few other issues that caught my eye. Once I'm comfortable w/ how the application in structured I'll circle back to this.
