### ISSUE TITLE
Photo upload doesn't work on Android

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#360]
# Description

Bug reported by user - photo submit doesn't work on Android

# Steps to reproduce

Head to submit page and tap the photo upload area:

<img width="381" alt="screen shot 2018-02-04 at 9 07 11 pm" src="https://user-images.githubusercontent.com/7832803/35781846-96964096-09ef-11e8-98ef-c8142563ab08.png">

# Expected Result

A photo selection UI comes up allowing you to select which images from your phone you'd like uploaded

# Actual Result

nothing happens

**Comment by r4v5** [comment]
If you don't have an android device handy, and don't currently have an emulator, and are familiar with Docker, https://github.com/butomo1989/docker-android is a way to get emulators for a bunch of different devices up and running quickly to test this, btw.

**Comment by redshiftzero** [comment]
Yep, just tried this on another Android phone and the photo upload worked fine. Needs more info to reproduce. Closing for now.
