### ISSUE TITLE
Header overlapping content

### ISSUE THREAD

**Issue by pierwill** [lucyparsons/OpenOversight#362]
At a small range of widths on my widescreen monitor, the [tutorial page](https://openoversight.lucyparsonslabs.com/tutorial) looks like this: 

(Eh, having issues with a screenshot. The top of the page is covering the LE note.)

**Comment by redshiftzero** [comment]
<img width="819" alt="screen shot 2018-02-16 at 9 17 55 pm" src="https://user-images.githubusercontent.com/7832803/36338252-df5c3678-135e-11e8-8f5a-76981e04a97d.png">
