### ISSUE TITLE
Add photo submission page for logged in users

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#371]
Some users of OpenOversight have detailed information about officers in their community, and want to upload this information, along with the photographs of the officer, all in one page. These photos will not need to go through the usual volunteer workflow as their identities are already known. Only accounts associated with a known user from the community should have this capability (e.g. #355) - administrators should determine this. 

On this submit page we should be able to submit all information about an officer:
* Photos
* Name
* Ethnicity
* Gender
* Links to lawsuits, videos, media articles (if #223 is implemented)
* Free text - for now we should just store this in the database - though we can display for coordinators/administrators on their officer profile

### User Stories

As a community member with knowledge of the police force, I should be able to submit photographs of officers I know along with all information about the officer in a single page.

**Comment by redshiftzero** [comment]
Some user feedback from Copwatch: videos should be related to an incident and then the officers should be associated with the incidents - i.e. we should store two new models, Videos and Incidents

**Comment by raq929** [comment]
Double-checking my understanding here: Area coordinators should be able to create new officers (in their department) and attach photos of them.

**Comment by redshiftzero** [comment]
Area coordinators should be able to both create and edit new officers and they should be able to add photos to any officers in their department (including ideally in the form when the new officer in created so they can do it in one place)

**Comment by raq929** [comment]
OK, cool. AC's can already add/edit officers since #428 was merged, so what I'm going to add here is the ability to add photos directly and the 'free text' section.
