### ISSUE TITLE
One-command deploys

### ISSUE THREAD

**Issue by r4v5** [lucyparsons/OpenOversight#38]
Once we have migrations and a local dev environment, we'll want the ability to deploy this thing in a far more straightforward manner than we currently have. I'm open to suggestions; I'm thinking either a rake task that rsyncs things or a capistrano setup, but that's because most of my deployment orchestration experience is in Ruby. For all I know, there's a better solution here, and if so, we should find it and use it.

**Comment by scuerda** [comment]
I've done a fair amount with `fabric` and it's fairly easy to work with. I've used it to do essentially what it sounds like is already being done (`git pull` followed by other commands).

One thing to consider is that now that travis close to being up and running, it might be nice to use those tools to test and deploy automatically. Not sure how that would work w/ `fabric`, but it would be easy enough with a shell script.

**Comment by freddymartinez9** [comment]
@scuerda if you can point me to some resources where this is set up, I can modify them and set them up. I've never used `fabric` but could figure it out with an existing example.

**Comment by scuerda** [comment]
I'll throw up a gist and share the link.

**Comment by scuerda** [comment]
@freddymartinez9 [Here](https://gist.github.com/scuerda/3d4aa909a8be00d27c2618d29d046d9b) is a variant of one for a CKAN project I manage.

This lets me deploy with `fab prod deploy` or dump and download the database with `fab prod backup`

[Here](https://gist.github.com/onyxfish/299803) is another one that is MUCH more robust, but maybe a bit dated at this point.

This has some nice things like rollback functions, etc. In general, it isn't too different from working with something like gulp/grunt.

**Comment by freddymartinez9** [comment]
thanks Sasha! assigning to myself and Mason.
