### ISSUE TITLE
Move codebase to Python3

### ISSUE THREAD

**Issue by b-meson** [lucyparsons/OpenOversight#388]

**Comment by r4v5** [comment]
iirc the only dependency blocking this is flask mailer; we’d want to find a replacement, which i started down the road to before getting overwhelmed by choices.

**Comment by pierwill** [comment]
All dependencies including dev ones installed successfully in a python3 virtual env.

**Comment by r4v5** [comment]
well shucks, I recalled incorrectly. lets do it then :) it might just motivate me to finish the chef cookbook for setting up servers.
(it’s also trivial to change that cookbook from py2 to py3 thanks to poise’s python cookbook)

**Comment by redshiftzero** [comment]
Python 3 is supported as of #552, the remaining task here is to use Python 3 in staging/prod

**Comment by McEileen** [comment]
Hey, if no one objects, I'm going to close this in the next day since we now support Python3.

**Comment by McEileen** [comment]
I'm closing this issue because we now support Python3.
