### ISSUE TITLE
add more details to contrib.md

### ISSUE THREAD

**Issue by judytuna** [lucyparsons/OpenOversight#389]
* download vagrant. what versions are confirmed to work or not work?
* download and start virtualbox. versions? 

explanations of how vagrant/virtualbox and python work
* on first run of `vagrant up`, it'll take a while to download ubuntu.
* the python package dependencies have already been installed in the vm.
* on the vm, the code lives in `/vagrant/OpenOversight`. cd there (after you've activated the virtual environment) in order to run things like `pytest`.
* actually.... it seems i can't run `pytest` in `/vagrant/OpenOversight` ... i need to be in `/vagrant/OpenOversight/tests` . (also, the test data was already seeded into a test database?)

**Comment by redshiftzero** [comment]
Thanks for writing these out - totally agree that the documentation here should be improved!

**Comment by r4v5** [comment]
This is definitely good feedback; we've needed to elaborate on CONTRIB.md for a while (and we'll probably turn it into a choose-your-own-adventure when the Docker (#341) dev environment gets merged).

I was the most recent one to poke around at tests that had to reference files, so I think I might have broken the "running pytest in /vagrant/OpenOversight" thing. I thought I managed to do the referencing in such a way that you can run `pytest` from there; could you elaborate a bit about what you're seeing? I want to avoid a "works on my machine" situation 😄

**Comment by judytuna** [comment]
how do i get out of this state, lol? (tried ctrl+c, escape, pressing Q, typing quit...)

<img width="569" alt="screen shot 2018-02-17 at 6 31 46 pm" src="https://user-images.githubusercontent.com/315395/36347638-ec447780-1410-11e8-8a4e-4740509a4c09.png">

**Comment by r4v5** [comment]
It should eventually respond to a ^C; worst case, you can disconnect from the `vagrant ssh` session by using the SSH escape key (press the enter key and then `~`) and a `.` to kill the session. (enter-tilde-dot, is what it is in my muscle memory). Once out, you can `vagrant ssh` back in and `killall python` to forcefully stop pytest.

**Comment by judytuna** [comment]
thanks! i killed the terminal window =P and restarted the vm. haha. 

ah, it is actually working for me in /vagrant/OpenOversight ... my bad xD
