### ISSUE TITLE
thumbnail officer photos should be centered

### ISSUE THREAD

**Issue by ssempervirens** [lucyparsons/OpenOversight#403]
as of right now, officer thumbnails are not centered. they should be, in order for the photo gallery to be useful. example: 
<img width="842" alt="screen shot 2018-02-27 at 9 15 16 pm" src="https://user-images.githubusercontent.com/20425838/36771160-8d301718-1c03-11e8-8ab8-a2aa7f8c7876.png">

**Comment by abandoned-prototype** [comment]
I have to assume this has been fixed, if not please create a new issue with steps to reproduce
