### ISSUE TITLE
Allow tagging multiple officers in one photo

### ISSUE THREAD

**Issue by magpiewings** [lucyparsons/OpenOversight#408]
Right now we don't allow duplicate uploads of photos, but most of our pictures depict multiple officers. We should allow multiple officers to be tagged, with a little "finished tagging" button once completed. (We will have to separately address how we want to handle pictures with officers from DIFFERENT departments, per #377)

**Comment by redshiftzero** [comment]
Good news - this is implemented! 

You can continue to add as many officer faces as you like by continuing to use:

![screen shot 2018-03-22 at 9 50 56 am](https://user-images.githubusercontent.com/7832803/37785147-a4ddd8f4-2db6-11e8-89bf-c79cb1175ef4.png)

And only when you click this button: 

![screen shot 2018-03-22 at 9 51 02 am](https://user-images.githubusercontent.com/7832803/37785180-b78f3948-2db6-11e8-816b-dea74b1b5739.png)

will you move on to the next image!
