### ISSUE TITLE
Add incident upload for area coordinators 

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#417]
We'd want to store only the public data:

* Date/time of incident (rounded to hour)
* Exact location (rounded to block)
* Incident report # (this is something that would be specific to the local organization, so they can check against their private report to look up e.g. witnesses of a specific incident) 
* Officers involved (link to officer ID) 
* License numbers
* Description of incident
* We do _not_ want to store the victim or witness information.

*Editable by:* Administrators, area coordinates (requires #355)

Copwatch Berkeley incident form for reference:

<img width="521" alt="screen shot 2018-04-11 at 9 19 37 pm" src="https://user-images.githubusercontent.com/7832803/38656250-24c0030e-3dce-11e8-9ec7-c97303a29985.png">

**Comment by raq929** [comment]
Branch on `trusted-user-upload` branch

**Comment by raq929** [comment]
Attribute description to Berkley CopWatch

**Comment by raq929** [comment]
What do you mean by `rounded to block` when you talk about the location?

**Comment by raq929** [comment]
Update: I'm doing `street`, `cross_street1`, `cross_street2`
