### ISSUE TITLE
Enable photo upload from the officer profile page

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#451]
I want to be able to browse to an officer's profile, and then from the profile page as an admin or AC, be able to add photos of that cop. 

For example, I added a news article about this cop https://openoversight.com/officer/21672 who got his girlfriend to shoot herself, and there is a photo of him in the linked article we could add to OO, it would be easiest to do this from the profile.

**Comment by redshiftzero** [comment]
Heads up there is a pending PR for this in #506

**Comment by abandoned-prototype** [comment]
Fixed by https://github.com/lucyparsons/OpenOversight/pull/506
