### ISSUE TITLE
Incident: Allow no license plates

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#457]
I get a CSRF error when I remove the single license plate area in the incident form: 

<img width="559" alt="screen shot 2018-06-03 at 10 59 44 pm" src="https://user-images.githubusercontent.com/7832803/40900735-e30341b4-6781-11e8-853b-9fb01a3dcb6a.png">

**Comment by raq929** [comment]
Sigh. I thought I had fixed that. Working on photos first, but then this is probably in my wheelhouse. :)
