### ISSUE TITLE
Add button for download of all department data

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#489]
For each department, it would be nice to have an endpoint for the download of all data from a given department in CSV format. Instead of dumping out all the photos, which is expensive for us, as a stopgap we could just dump out the URLs

**Comment by camfassett** [comment]
Should we close #385 and instead open an issue for each endpoint?

**Comment by redshiftzero** [comment]
sorry my bad, I should not have named this endpoint, more like "button" for download of all department data. I think an API is worth doing but many orgs/communities that are onboarded to OpenOversight that might be concerned about LPL control over data aren't going to be able to do API requests due to the technical barrier
