### ISSUE TITLE
Implement content warnings

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#493]
We should definitely have content warnings on some videos of police incidents. This is something that @nmorduch noted in the mockup in #473. For videos, we should add a column that is `has_content_warning` or similar that determines whether this greyed out box will appear: 

<img width="1000" alt="screen shot 2018-07-08 at 3 22 46 pm" src="https://user-images.githubusercontent.com/7832803/42424544-cee39452-82c2-11e8-9450-a2b38b7dd164.png">

For simplicity we could just have some generic text appear: "This video may be disturbing to some viewers.". The form for submitting videos associated with officers and incidents should have a checkbox (checked by default?) indicating whether the content warning should be in place for the video in question.

**Comment by nmorduch** [comment]
I agree about switching to generic text, especially because it would be nice for the caption to remain visible after the content warning screen is dismissed. I have been thinking that this was a silly thing that I overlooked!
