### ISSUE TITLE
Footer should not collapse on large screen

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#496]
The footer collapses even when the screen is not particularly small: 

<img width="871" alt="screen shot 2018-07-08 at 3 39 29 pm" src="https://user-images.githubusercontent.com/7832803/42424688-37b2b8d0-82c5-11e8-889a-b8c26cd14460.png">

Let's modify the collapsing here to stay three column:

<img width="1224" alt="screen shot 2018-07-08 at 3 47 45 pm" src="https://user-images.githubusercontent.com/7832803/42424738-46aebd7e-82c6-11e8-85ec-c53591de8290.png">

(with less whitespace)

**Comment by McEileen** [comment]
I'm interested in working on this issue.
