### ISSUE TITLE
Incident view does not indicate required fields

### ISSUE THREAD

**Issue by b-meson** [lucyparsons/OpenOversight#505]
I think "description" is a required field but it is unclear. Here is a screenshot, I filled out a title but not a description. It is confusing because we can also add a description to a link but I don't know if we should do both? 

<img width="653" alt="screen shot 2018-07-09 at 2 42 13 pm" src="https://user-images.githubusercontent.com/3100220/42477597-8819408e-8386-11e8-9a38-55ae546b0da4.png">

**Comment by b-meson** [comment]
After opening this ticket, I went back and added a description and a filler report number (which may be required?) but I am still seeing the "this is a required field". I am confused and this happened the last time I tried to add an incident which lead me to not fill it out last time.

**Comment by redshiftzero** [comment]
thanks for filing this! one reasonable thing to do here is to denote which fields are required using a red asterisk (or similar)

**Comment by b-meson** [comment]
For others, we currently require Location Information for adding an incident (which I don't think we actually need to do for every PD. 

```
class LocationForm(Form):
    street_name = StringField(validators=[Required()], description='Street on which incident occurred. For privacy reasons, please DO NOT INCLUDE street number.')
    cross_street1 = StringField(validators=[Required()], description="Closest cross street to where incident occurred.")
    cross_street2 = StringField(validators=[Optional()])
    city = StringField(validators=[Required()])
    state = SelectField('State', choices=STATE_CHOICES,
                        validators=[AnyOf(allowed_values(STATE_CHOICES))])
    zip_code = StringField('Zip Code', validators=[Regexp('^\d{5}$', message='Zip codes must have 5 digits')])
````

**Comment by nmorduch** [comment]
I have also been running into similar problems with this form and which fields are required.

**Comment by redshiftzero** [comment]
and addresses should be optional... running into this and will fix today
