### ISSUE TITLE
bulk update management command

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#525]
When we get new rosters via FOIA, we should update the data on the officers via a bulk update command. The would obviate the need for volunteers to manually do this work via the web application. 

We could specify department as an argument to this management command, and then pass a CSV in the same format as #524. 

We'd need to select the relevant officer based on all data we have on them, e.g. first name, middle initial / name, last name, gender, race (+ anything else persistent we have stored). If we filter by department this is hopefully sufficient for a join (testing needed).

**Comment by dismantl** [comment]
Fixed by #524. The bulk upload command also updates existing officers.
