### ISSUE TITLE
Customizable, per-department resource page

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#528]
For each department, we should have the ability to add a customizable resource page that contains information like:

- How you file a complaint, and what a person should be aware of prior to filing a complaint (i.e. many people don't know that the complaints process is often totally broken and may result in additional risks to them)
- Other groups in that city that they can go to for support

This should be editable by area coordinators and admins.

**Comment by abandoned-prototype** [comment]
This seems to be a duplicate of https://github.com/lucyparsons/OpenOversight/issues/381
