### ISSUE TITLE
Timeout Error on vagrant up

### ISSUE THREAD

**Issue by NatureBoyRS** [lucyparsons/OpenOversight#542]
Hey all,

I'd like to contribute, and finally have a working computer -- but when I run vagrant up, I get the following error: 

![2018-08-16-225929_1366x768_scrot](https://user-images.githubusercontent.com/42425804/44247985-9b329e00-a1ad-11e8-836c-7fdbf524a390.png)

I've tried a couple of times, follows the contrib instructions. Any suggestions?

**Comment by abandoned-prototype** [comment]
Hi,
I don't have much experience with vagrant, but I am assuming there are a few things you can try. First of, is the image running in VirtualBox? You can see that by starting the VirtualBox GUI, where you should find an entry like "OpenOversight_default_" followed by some numbers, does it say "Running" below, or something else?
Which Operating system are you using and is VirtualBox up to date?
Did you try googling for the error message? I found https://stackoverflow.com/questions/23690124/vagrant-up-timeout and https://stackoverflow.com/questions/23293071/timed-out-while-waiting-for-the-machine-to-boot-when-vagrant-up for example, maybe one of the answers there help

**Comment by b-meson** [comment]
i have had this issue before but restarting the OpenOversight VM and then doing `vagrant ssh` made it work. Have you tried that?

**Comment by NatureBoyRS** [comment]
No friends, I was considerably more bone-headed than that ... apparently turning virtualization, in the BIOS, on, helps !

Thank you! Off to explore!!

**Comment by b-meson** [comment]
@NatureBoyRS I literally did the exact same time.
