### ISSUE TITLE
Configure markdown support for sphinx documentation 

### ISSUE THREAD

**Issue by ssempervirens** [lucyparsons/OpenOversight#561]
Working on the OO docs and I know I for one would rather write in md than html. Seems to be an easy change in the sphinx config file to add md support. 

From sphinx docs: 
Install recommonmark:

```pip install recommonmark```

Add the Markdown parser to the source_parsers configuration variable in your Sphinx configuration file:

```source_parsers = {
   '.md': 'recommonmark.parser.CommonMarkParser',
}
```

You can replace .md with a filename extension of your choice.

Add the Markdown filename extension to the source_suffix configuration variable:

```source_suffix = ['.rst', '.md']```

**Comment by redshiftzero** [comment]
If peeps prefer Markdown, then that's cool with me!
