### ISSUE TITLE
Use pipenv

### ISSUE THREAD

**Issue by b-meson** [lucyparsons/OpenOversight#565]
As a developer I want my depencies up to date and pinned to hashes.

**Comment by redshiftzero** [comment]
Hey so I have been using Pipenv in [other](https://github.com/freedomofpress/securedrop-client) [projects](https://github.com/freedomofpress/securedrop-proxy), and I find that while there are some nice features (e.g. `pipenv check`) it breaks quite a lot and I don't think the benefits justify the effort here (note that we would still need to generate `requirements.txt` during deployment so we'd want to also modify the deployment process (or have duplicate requirements files (confusing/bad)).

**Comment by redshiftzero** [comment]
What do you think?

**Comment by b-meson** [comment]
So yeah, I notice we have `dev-requirements.txt` and a `requirements.txt` and I don't know that pipenv has a great way of handing multiple requirements files. I thought this issue would be fairly small to do but I don't think its super important. Closing as _won't fix_
