### ISSUE TITLE
Set up Travis and Coveralls

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#57]
Set up travis and coveralls to run our tests. needs to be done once we make the repo public so we can get that free service

**Comment by redshiftzero** [comment]
Ok so I started looking at this (in branch `setup-travis-coveralls`) and quickly realized that our nice vagrant setup doesn't work on Travis. I'm going to assign @r4v5 and @freddymartinez9 since y'all are better for this task, so if one of you could take a look at this it would be :+1:. Else I will return to it once I've implemented some of the issues tagged with high priority. Feel free to use that branch or feel free to just blow it away

**Comment by scuerda** [comment]
@redshiftzero I am trying to work travis integration into the pytest branch that I'm working on. Oddly I am currently getting a coverage report (which means tests are being run), but the actual testing is breaking slightly. If @r4v5 and @freddymartinez9 have other priorities, I'm happy to keep at this.

**Comment by scuerda** [comment]
Ok, I have travis and coveralls integrating and correctly [reporting](https://coveralls.io/github/scuerda/OpenOversight?branch=generate-test-data) in [this](https://github.com/scuerda/OpenOversight/tree/generate-test-data) branch. 

As per my comments on #108, the application structure has been modified to use the factory pattern. This is likely going to require a number of changes in deployment and it's probably best to make sure test coverage is at 100% before doing so. That said I'll am going to merge in the upstream work from development and start preparing this for a PR.

**Comment by redshiftzero** [comment]
Sounds great @scuerda - let us know if you run into issues, happy to help.
