### ISSUE TITLE
Missing data points should be displayed as Unknown rather than None

### ISSUE THREAD

**Issue by dismantl** [lucyparsons/OpenOversight#570]
Officer profiles and the summary listings on the browse page currently show missing data points as "None", for instance race, gender, or birth year. It would be clearer and more accurate to display them as "Unknown". 

![image](https://user-images.githubusercontent.com/2007008/48366643-7d75b780-e67c-11e8-8a07-e84bffe22195.png)

**Comment by jrabbit** [comment]
![image](https://user-images.githubusercontent.com/178803/50065532-f3da6d80-0184-11e9-9578-f840c32aa799.png)
 Which fields still need this?

**Comment by dismantl** [comment]
This appears to be fixed.
