### ISSUE TITLE
Remove blank space on officer profile when no photo available

### ISSUE THREAD

**Issue by dismantl** [lucyparsons/OpenOversight#571]
For desktop display, officer profiles that don't have any tagged photos have a big blank space on the page that feels awkward. I would suggest that blank space is either removed, or replaced with a "No photo available" silhouette image.

**Comment by dismantl** [comment]
Also, and this is purely my personal opinion, I would prefer a different silhouette placeholder photo for the browse view. The noun project has some options: https://thenounproject.com/search/?q=police. Also a google image search for "police silhouette" offers some more options.

**Comment by sibrahi5** [comment]
Could use logos from: https://github.com/lucyparsons/OpenOversight/issues/253
