### ISSUE TITLE
Per-department configurable ranks

### ISSUE THREAD

**Issue by dismantl** [lucyparsons/OpenOversight#572]
Each police department may have a different set of ranks. Instead of hardcoding the list in `choices.py`, it would be good to allow the admin of a department to input an ordered list of ranks. Maybe this could be included on a per-department settings page of some sort?

**Comment by dismantl** [comment]
The department-specific list of ranks should presumably be stored in the database for persistence. I would also say the department edit page (e.g. `/department/1/edit`) is probably the best place in the UI to configure the list of ranks.

Another idea is to add a CLI command to read in a list of ranks from a text file and apply it to the chosen department.

**Comment by McEileen** [comment]
@dismantl Since #662 was merged, which contained the changes from #619, can we close this issue?

**Comment by redshiftzero** [comment]
good flag @McEileen, closing!
