### ISSUE TITLE
Delete deprecated scripts in `database` folder

### ISSUE THREAD

**Issue by McEileen** [lucyparsons/OpenOversight#577]
I was looking at the `database` folder and the `README` indicates that every sql script except for `populate_officer_roster_and_assignment.sql` is deprecated.  Should we delete all of the other sql scripts in the `database` folder?

**Comment by McEileen** [comment]
It looks like the materials in `OpenOversight/etl/chicago` are also out of date.  Could a project maintainer please okay deleting these, along with the old scripts in the `database` folder?  I don't want to remove something we could need in the future.  Thanks!

**Comment by redshiftzero** [comment]
Hey yep - we can blow away the `etl` folder and we can blow away the `*sql` scripts in the `database` folder. These are from the very early days of me messing with the roster data we had (prior to there being a Flask application). Now we can create the database using the sqlalchemy metadata, and load officers via the manage.py commands or the admin functionality in the web application. Feel free to propose a PR for this and I will approve!

**Comment by redshiftzero** [comment]
Closed by #590
