### ISSUE TITLE
Delete ruby-version

### ISSUE THREAD

**Issue by McEileen** [lucyparsons/OpenOversight#578]
@r4v5 Since you [deleted the vagrant env](https://github.com/lucyparsons/OpenOversight/commit/f07d6174c8a2a03e74b5e2f1ccc5e1e4eb471daa), can we delete the ruby version file?  It seems like it was only needed for the vagrant env.

**Comment by r4v5** [comment]
Yep, wipe it.

**Comment by redshiftzero** [comment]
Closed by #590
