### ISSUE TITLE
Write migration to remove period placeholders for officers that don't have a middle name

### ISSUE THREAD

**Issue by McEileen** [lucyparsons/OpenOversight#580]
Previously, middle name was a required field for officers.  To get around this, we used `.` or `..` as placeholders for officers who didn't have middle names.  The below screenshot shows an example.

![oomiddlenameperiods](https://user-images.githubusercontent.com/5529982/49763761-2ec73780-fc93-11e8-9c84-e04c2588e6cf.png)

Now that middle name is an optional field for officers, we can write a migration to remove the period placeholders.

Issue task
- [ ]Write migration to remove `..` and `.` as officers' middle names

**Comment by camfassett** [comment]
Hey @McEileen! Sorry! This is not a bug. The periods (sometimes one, sometimes two) are there intentionally, to indicate that the officer did NOT have a MN on the roster we were given. At the time, I believe the MN field was not optional, and @redshiftzero decided that periods would be a decent placeholder for now.

**Comment by redshiftzero** [comment]
So the task here is to go through and remove all these `.`s?

**Comment by camfassett** [comment]
Yes, I believe that's the task here

**Comment by McEileen** [comment]
Ahhhh, okay!  I didn't realize that.  I can edit the issue to make it "write a migration to remove periods as middle name placeholders."  Does that sound good?

**Comment by redshiftzero** [comment]
yep ! :+1:
