### ISSUE TITLE
Tweak incident section of officer profile

### ISSUE THREAD

**Issue by McEileen** [lucyparsons/OpenOversight#581]
I'm still feeling out how I feel about this potential change, and I think it overlaps with potential changes proposed in #473.  Feedback would be appreciated!

Currently, if someone is viewing an officer profile, and the incident description doesn't fit in the description box, the description is cut off.  A user then has to click on the "Incident" link, which loads the separate incident page, to read the rest of the description.  There's an example in the below screenshot.

![incidentdescription](https://user-images.githubusercontent.com/5529982/49765568-887e3080-fc98-11e8-840a-51e5ab0ae5be.png)

I like the idea of adding a "read more" hyperlink or button at the end of any description that doesn't fit in the description box.  A user could click on "read more" and finish reading the description without navigating to a separate page.  Thoughts?

**Comment by dismantl** [comment]
Maybe the "read more" link could just expand the section via javascript to show the whole description? That way we can avoid a page load.

**Comment by McEileen** [comment]
Yes, that's what I was picturing as well.
