### ISSUE TITLE
Fix bug where last name and first name are switched for UC Berkeley Officer

### ISSUE THREAD

**Issue by McEileen** [lucyparsons/OpenOversight#584]
This officer profile has switched the officer's first and last name.  https://www.openoversight.com/officer/24830  I confirmed the error by locating "Brendan Tinney" on the UCPD directory page. https://ucpd.berkeley.edu/directory

The same error occurred here for Karla Rush. https://www.openoversight.com/officer/24827  I also located Rush on the UCPD directory page. https://www.openoversight.com/officer/24827

**Comment by camfassett** [comment]
So, I fixed Brendan Tinney's profile, but I get an internal server error when I try to update Karla Rush's. 
![screenshot from 2019-02-16 11-22-12](https://user-images.githubusercontent.com/20425838/52902331-3f3ce680-31dd-11e9-9078-f79f7d30be5a.png)

**Comment by abandoned-prototype** [comment]
I fixed that particular issue with Karla Rush, no server error this time. If this happens on a larger scale, the `advanced-csv-import`command could be used to fix it
