### ISSUE TITLE
Incorrect photo on officer profile

### ISSUE THREAD

**Issue by McEileen** [lucyparsons/OpenOversight#585]
(Possibly connected to issue #363 and the ability to flag photos?)

This photo appears to be mistakenly placed on the officer profile.  https://www.openoversight.com/officer/12086  The officer is listed as black and female, but the individual officer is white and male.

**Comment by brianmwaters** [comment]
Perhaps we need a feature for folks to report findings like this (maybe after a certain amount of reports, the photo gets removed, or something)?

**Comment by McEileen** [comment]
Yeah, I think that if we're going to open it up for anyone to report incorrect photos, there should be some sort of numeric cut-off (say, three reports) before the photo gets reviewed.  I'm concerned that if there's no such threshold, then bad actors who oppose OO's mission might flag valid photos.  However, we could also set a lower threshold for registered volunteers or admins.  Thoughts?

**Comment by camfassett** [comment]
At this stage of the project, I don't anticipate that we have significant enough usage that we would get three reports on a single officer photo, and if we did, it would probably not be for some time. To allow us to act quickly to respond to remedy incorrect data, and I think it would make sense to have an alert after just one flag/report sent to all admins, or people that we designate (like maybe you, Jen, myself, Freddy, Sanjin or whoever from LPL would have capacity to fix the problem.

**Comment by McEileen** [comment]
Good point that we probably wouldn't have enough usage to get three reports on a single officer photo.  :+1: to all you said above.

**Comment by sibrahi5** [comment]
Profile image was removed. #363 takes into consideration flagging photos, which is better.
