### ISSUE TITLE
Update the "about" page with current city info

### ISSUE THREAD

**Issue by McEileen** [lucyparsons/OpenOversight#588]
Currently, the [OpenOversight about page](https://www.openoversight.com/about) says that OpenOversight will launch in NYC in fall 2018.  Since we are past fall 2018 and OO has launched in NYC, we should update this.

Additionally, the about page makes no mention of the Baltimore OO instance.  I skimmed #515 and I'm under the impression that Baltimore OO will be hosting their own separate OO instance at a different url.  Is this correct?  

If so, do we want to currently put a line like `An instance of OpenOversight will be launching in Baltimore in the winter of 2018/2019` and then link to the Baltimore instance from the OO about page once the Baltimore instance is up?  (@dismantl, your input on this would be very helpful!)

**Comment by dismantl** [comment]
@McEileen that's correct, we are launching our own (somewhat modified) instance. Hopefully in January if all goes well.
