### ISSUE TITLE
Editing officer with blank UID results in error

### ISSUE THREAD

**Issue by dismantl** [lucyparsons/OpenOversight#610]
Departments without unique internal identifiers shows the field as 'None' on officer profiles:
![image](https://user-images.githubusercontent.com/2007008/50540399-172af280-0b5f-11e9-8f1f-c161bdd8486e.png)

However, if you edit and save an officer's profile, it will save the UID as an empty string rather than NULL. This causes a problem when you edit a second officer's profile since the database will reject a second blank string unique_internal_identifier, since that field has a unique constraint:

```
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (psycopg2.IntegrityError) duplicate key value violates unique constraint "ix_officers_unique_internal_identifier"
DETAIL:  Key (unique_internal_identifier)=() already exists.
 [SQL: 'UPDATE officers SET unique_internal_identifier=%(unique_internal_identifier)s WHERE officers.id = %(officers_id)s'] [parameters: {'unique_internal_identifier': '', 'officers_id': 219}]
```

**Comment by redshiftzero** [comment]
closed by #612
