### ISSUE TITLE
Unable to remove links from officer profiles

### ISSUE THREAD

**Issue by dismantl** [lucyparsons/OpenOversight#611]
After adding some links to an officer profile, I go to the edit officer page and remove the links and click Update. The action appears to be successful, yet the links remain on the officer profile.

**Comment by dismantl** [comment]
If we move the links form to its own page (a la #574) and add the little edit and delete buttons to each entry (like Notes and Descriptions), that would probably be a good way to solve this.

**Comment by redshiftzero** [comment]
closed by #612

**Comment by dismantl** [comment]
#612 failed to resolve this, so reopening.

**Comment by abandoned-prototype** [comment]
FIxed by https://github.com/lucyparsons/OpenOversight/pull/646
