### ISSUE TITLE
CONTRIB.md out failures for env variables

### ISSUE THREAD

**Issue by freddymartinez9** [lucyparsons/OpenOversight#64]
currently if you run `echo "localhost:5432:openoversight-dev:openoversight:terriblepassword" > ~/.pgpass` more than once, it will throw a "too many keys" value because it appends it to  the pgpass file. I manually edited it and removed all but one lines and it worked fine after a `soure ~/.bashrc` so I know its the >> append redirect.

**Comment by redshiftzero** [comment]
fixed in #65
