### ISSUE TITLE
Update CPD roster

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#66]
The most recent "Date of Employment" in our current roster is "2015-12-14 00:00:00". Time to update! More broadly, this is something that we will need to do periodically to keep data fresh. Also, we might want to consider adding photographs and A&A sheets to the list of things to FOIA for this project (so that we have information about where an officer is assigned in the city - this is necessary for #12).

**Comment by freddymartinez9** [comment]
https://www.muckrock.com/foi/chicago-169/cpd-badge-numbers-29489/

**Comment by redshiftzero** [comment]
As discussed at the dev meeting, here is my original FOIA for the roster (cc @JoshuaOpolko):

> To whom it may concern:
> 
> Pursuant to the Illinois Freedom of Information Act (5 ILCS 140/1 to
> 11), I hereby request the following records:
> 
> The current roster of sworn officers in the Chicago Police Department.
> These documents should be sufficient to show:
> 
> * Names of each sworn police officer. There should be at least 13976
> rows in this dataset.
> * Current badge number
> * Current rank
> * Gender
> * Race
> * Date of employment
> 
> The requested documents will be made available to the general public,
> and this request is not being made for commercial purposes.
> 
> In the event that fees cannot be waived, I would be grateful if you
> would inform me of the total charges in advance of fulfilling my
> request. I would prefer the request filled electronically in Excel or
> plaintext format if available, and by e-mail attachment if available
> or CD-ROM if not.
> 
> Thank you in advance for your anticipated cooperation in this matter.
> I look forward to receiving your response to this request within 5
> business days, as the statute requires.
> 
> Sincerely,
> 
> Jennifer Helsby

**Comment by freddymartinez9** [comment]
Current star numbers `[here](https://www.muckrock.com/foi/chicago-169/cpd-badge-numbers-29489/)`. However we definitely need to have these automated or send this request every 6 months.

**Comment by redshiftzero** [comment]
This was marked in progress but hasn't been addressed since the initial launch of OpenOversight so we should get to this soon - marking as high priority. Note that now the ability to update the officers assignments as well as add new officers is now available to all admins, so this does not require any special technical skills to take on.

**Comment by rajivsinclair** [comment]
hey hey! We recently received data from CPD for all officers’ badge numbers over time. Haven’t fully reviewed and processed it yet, but I wanted to share it with y’all in case you’re working on an update for OpenOversight: [InvisibleInstitute_DataInfoforallswornCPDofficers-UPDATEv2.xlsx](https://www.dropbox.com/s/tbyb7vl3yhtute5/14532-P540798-InvisibleInstitute_DataInfoforallswornCPDofficers-UPDATEv2.xlsx?dl=0) 

Also, if you’d like to see the FOIA response letter, here it is: [Response.doc](https://www.dropbox.com/s/ctoi14d4nycpjj6/Response.doc?dl=0)

**Comment by abandoned-prototype** [comment]
Updating here to say that this task has finally been completed. An updated roster has been imported to production.
Thanks to @rajivsinclair for providing very recent assignment data. The work on merging is documented here: https://github.com/abandoned-prototype/OpenOversight_data/tree/main/CPD_August_2020. The files starting with "4_out_select_" are those that have been imported via the `advanced_csv_import` command.
Still an open question is how to keep the roster up to date. I will open an issue on that.
