### ISSUE TITLE
Editing incident and adding additional information wipes city/state field

### ISSUE THREAD

**Issue by ssempervirens** [lucyparsons/OpenOversight#661]
When editing an existing incident to add additional info such as a link, the city/state fields are wiped and the user must manually re-add those each time. Also, the placement of the "must fill out field" note could be placed better, but that's less critical
<img width="621" alt="Screen Shot 2019-04-26 at 15 12 32" src="https://user-images.githubusercontent.com/20425838/56831020-0604a080-6836-11e9-83e5-e1cf9693d4ad.png">

**Comment by abandoned-prototype** [comment]
Can't reproduce. Looks like the city and state was never set in this case
