### ISSUE TITLE
Release OpenOversight 0.6

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#664]
This is a tracking ticket for visibility of the things we need to be aware of for the next deployment of OpenOversight to openoversight.com: 

# For pre-release testing on staging

- [x] Test/QA deployment process for static assets (#658) - done, automated as part of new CD pipeline
- [ ] Manually add ranks to departments (`RANK_CHOICES` is no longer hardcoded and is customized per-department)
- [ ] Test upgrade in the dev env from master to develop - this tests that the database migrations will apply cleanly

# Release process

- [x] Make PR into `master`
- [ ] Approve said PR
- [ ] Maybe make some hotfixes to the deployment job since this'll be the first deploy to production via the deploy on merge circle CI job 😅 
- [ ] Manually add ranks to departments (`RANK_CHOICES` is no longer hardcoded and is customized per-department)

**Comment by r4v5** [comment]
oops i accidentally done did this

**Comment by redshiftzero** [comment]
just added 0.6.0 tag on main for posterity, closing this
