### ISSUE TITLE
PNG of database relationships is out of date

### ISSUE THREAD

**Issue by McEileen** [lucyparsons/OpenOversight#683]
The database schema is out of date, for example, the `department` model doesn't include the field `unique_internal_identifier_label`.

**Comment by McEileen** [comment]
I thought the schema represented the relationships established in the `develop` branch.  I think what you're saying is that it actually represents the relationships in `master`, which means I was mistaken in saying that the schema was out of date.

**Comment by redshiftzero** [comment]
After offline discussion, the problem @McEileen is raising here is that https://github.com/lucyparsons/OpenOversight/blob/develop/database/relationships.real.large.png is out of date

**Comment by michplunkett** [comment]
Once this PR is figured out, I'll update the PNG: https://github.com/lucyparsons/OpenOversight/pull/992
