### ISSUE TITLE
bulk-add-officers command - problems

### ISSUE THREAD

**Issue by abandoned-prototype** [lucyparsons/OpenOversight#696]
Working with the bulk-add-officers command I ran into two issues so far.

* When `job_title` isn't provided, no `assignment` is created in the database for that officer, which leads to a problem with the officer listing in `/department/<id>`. The template assumes that there is at least one assignment for each officer. Current workaround is to always provide `job_title` in the csv, and use `"Not Sure"` if the rank/job title is unknown.

* When using the `mm/dd/yyyy` format for the hiring date the command is not idempotent, the update fails, because the date is transformed into `yyyy-mm-dd` and a string comparison fails: `Exception: Officer xx has differing employment_date field. Old: 2005-03-28, new: 3/28/2005`

**Comment by StringCheez** [comment]
I've implemented a first pass at correcting these bugs, but I'm getting a permission error when attempting to push to a feature branch:

```
remote: Permission to lucyparsons/OpenOversight.git denied to StringCheez.
fatal: unable to access 'https://github.com/lucyparsons/OpenOversight.git/': The requested URL returned error: 403
```

I'm not sure if I'm doing something wrong, or if I need to be allowed to create branches. Should I fork the project and make my changes there?

**Comment by abandoned-prototype** [comment]
Hi @StringCheez. Welcome!
>I'm not sure if I'm doing something wrong, or if I need to be allowed to create branches. Should I fork the project and make my changes there?

You are correct, please create a branch on your fork. Unfortunately this isn't mentioned correctly in the contribution guide

**Comment by StringCheez** [comment]
Will do, thanks for the info!
