### ISSUE TITLE
Find Officer Form's fields are off-center when the browser is at half-screen

### ISSUE THREAD

**Issue by McEileen** [lucyparsons/OpenOversight#697]
When the browser is full-screen, the form fields are centered in the form.
![OfficerFormCentered-resized](https://user-images.githubusercontent.com/5529982/73143496-a5c2b980-4068-11ea-9d00-e5d40566f4ca.png)

When the browser is set to half-screen, the form fields are off-center.

![FindOfficerFormOffcentered2-resized](https://user-images.githubusercontent.com/5529982/73143473-57adb600-4068-11ea-8006-df3a2f54e244.png)

**Comment by michplunkett** [comment]
No longer an issue with the switch to Bootstrap5: https://github.com/lucyparsons/OpenOversight/issues/1105
