### ISSUE TITLE
Bug: Deleting a rank through the department /edit page doesn't persist

### ISSUE THREAD

**Issue by McEileen** [lucyparsons/OpenOversight#708]
I found this bug while doing testing before releasing to prod for #664.  If a user deletes a rank on the department `edit` page, the change doesn't persist.  The relevant code is linked [here](https://github.com/lucyparsons/OpenOversight/blob/develop/OpenOversight/app/main/views.py#L408).

**Comment by r4v5** [comment]
https://github.com/lucyparsons/OpenOversight/blob/develop/OpenOversight/app/main/views.py#L432 do we need to commit() the db session after the query is execute()d here?

**Comment by McEileen** [comment]
Hey, I unassigned myself because computer difficulties prevent me from contributing to OpenOversight right now.  I'm working on getting that fixed ASAP.  If this is still open when I have my computer working again, then I'll reassign myself.  Until then, other people are also welcome to work on this bug.

**Comment by McEileen** [comment]
@r4v5 It was a different issue.  I fixed it and I'm going to submit a PR now.
