### ISSUE TITLE
Display "No Results Found" more prominently

### ISSUE THREAD

**Issue by ebaxter** [lucyparsons/OpenOversight#712]
When a search returns no results, the "No Results Found" message appears in the top left corner and is easy to miss.  The eyes are drawn instead to the full list of officers which is displayed in the center of the screen.  For a careless newb (like myself) it makes it appear as if the search didn't work.  It might be helpful to display "No Results Found" more prominently, or to not show the full list of officers when a search returns no results.

**Comment by redshiftzero** [comment]
thanks for filing, yeah this should be clearer - marking this as good first issue

**Comment by redshiftzero** [comment]
turns out this is fixed in `develop`, just not deployed yet, closing
