### ISSUE TITLE
permission denied in dev env when creating assets

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#713]
Someone reported this to me privately, and I vaguely recall someone else ran into this months ago, please comment if you remember the resolution. 

The person was running Debian, ran `make dev` and the dev env started without the CSS styles loaded. Rerunning `make assets` resulted in this permissions error:

```
$ make assets
docker-compose run --rm web yarn build
WARNING: The AWS_ACCESS_KEY_ID variable is not set. Defaulting to a blank string.
WARNING: The AWS_SECRET_ACCESS_KEY variable is not set. Defaulting to a blank string.
WARNING: The AWS_DEFAULT_REGION variable is not set. Defaulting to a blank string.
WARNING: The S3_BUCKET_NAME variable is not set. Defaulting to a blank string.
WARNING: The APPROVE_REGISTRATIONS variable is not set. Defaulting to a blank string.
Starting openoversight_postgres_1 ... done
yarn run v1.22.4
warning package.json: No license field
$ node-sass --build --recursive OpenOversight/app/static/scss/index.scss -o OpenOversight/app/static/dist
Rendering Complete, saving .css file...
Error: EACCES: permission denied, mkdir '/usr/src/app/OpenOversight/app/static/dist'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Makefile:23: recipe for target 'assets' failed
make: *** [assets] Error 1
```

**Comment by brianmwaters** [comment]
The workaround hack I use at the moment is

`mkdir OpenOversight/app/static/dist/
chown 33 OpenOversight/app/static/dist/`

`make assets` and `make cleanassets` then work as expected.

There is a similar issue with the `container_data` folder created by postgres.

Maybe there is some way to fix this with user namespaces or something. I am not a docker expert by any means.

**Comment by brianmwaters** [comment]
I get a lot of errors with `make test`:

[test.log](https://github.com/lucyparsons/OpenOversight/files/4741421/test.log)

**Comment by peculater** [comment]
Good catch.  Turns out selenium+xvfb+firefox also needed some negotiating in order to run comfortably as a non-root user.  I've pushed a commit to #714 that lets me run `make test` without errors.

**Comment by brianmwaters** [comment]
I realize now that I commented on the issue, and not the pull request. I will test your fix in a sec here.
