### ISSUE TITLE
create unit view of officers

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#733]
We have a way to [create units via the web UI](https://github.com/lucyparsons/OpenOversight/blob/develop/OpenOversight/app/main/views.py#L571-L587), but not an easy way to - for a given unit - see which cops are assigned to it, along with [any other information stored about the unit](https://github.com/lucyparsons/OpenOversight/blob/develop/OpenOversight/app/models.py#L189-L198). 

This should be viewable by non-logged in users.

**Comment by fritzdavenport** [comment]
Looking to get started on this. Question, though, doesn't look like units *have* officers in the db schema?
https://disman.tl/oo-docs/tables/departments.html

**Comment by brianmwaters** [comment]
@dismantl i didn't even know you were hosting these docs. How up to date are they?

**Comment by dismantl** [comment]
oh sorry those docs are ages out of date, I forgot they were still online. They were generated using [schemaspy](https://hub.docker.com/r/schemaspy/schemaspy/) when I wanted to get a visualization of the db schema. If that's helpful for others I could submit a PR to add a Makefile target to autogenerate those docs from a dev environment, [kinda like this](https://github.com/dismantl/CaseHarvester/blob/5b674b49825da14b866f3572c6c528cee3295b82/Makefile#L87).

**Comment by fritzdavenport** [comment]
@brianmwaters @dismantl no worries on it. There's also an [image of the schema in the repo](https://github.com/lucyparsons/OpenOversight/tree/develop/database) - dunno if that's up to date either :) I poked around in the dev db, though, and verified what I needed (and will be adding a make target to get onto the docker-compose db in my PR)

**Comment by brianmwaters** [comment]
@fritzdavenport you can also check out https://github.com/lucyparsons/OpenOversight/blob/develop/OpenOversight/app/models.py, or use a tool like `psql` to connect to the database locally, after running `make start`. The creds are in https://github.com/lucyparsons/OpenOversight/blob/develop/docker-compose.yml.

**Comment by fritzdavenport** [comment]
Thanks @brianmwaters :+1: 
PR incoming, for whoever is ready for it
