### ISSUE TITLE
Issue getting dev server running

### ISSUE THREAD

**Issue by jclr** [lucyparsons/OpenOversight#754]
When following the dev instructions, I get the following error:

```
Starting openoversight_postgres_1 ... done
Traceback (most recent call last):
  File "../create_db.py", line 2, in <module>
    from OpenOversight.app import create_app
  File "/usr/src/app/OpenOversight/app/__init__.py", line 103, in <module>
    app = create_app()
  File "/usr/src/app/OpenOversight/app/__init__.py", line 32, in create_app
    from .models import db  # noqa
  File "/usr/src/app/OpenOversight/app/models.py", line 15, in <module>
    db = SQLAlchemy()
  File "/usr/local/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 715, in __init__
    self.Model = self.make_declarative_base(model_class, metadata)
  File "/usr/local/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 797, in make_declarative_base
    model.query_class = self.Query
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/ext/declarative/api.py", line 79, in __setattr__
    _add_attribute(cls, key, value)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/ext/declarative/base.py", line 796, in _add_attribute
    type.__setattr__(cls, key, value)
TypeError: can't apply this __setattr__ to DefaultMeta object
make: *** [create_db] Error 1
```

**Comment by r4v5** [comment]
Hi there! This is definitely a bug in the latest dev branch; I'll be working on fixing it tonight. While we look into that, the parent commit before the most recent merge (f6675899f4461a7b9bdde511502f37b7e9853161) should work for exploration purposes. You can check it out via `git checkout f6675899f4461a7b9bdde511502f37b7e9853161` from your repository, and it's a perfectly reasonable thing to create a new branch from (via `git checkout -b new-branch-name`) if you are interested in development.
My apologies for the bad timing!

**Comment by r4v5** [comment]
Well, the good* news is that it [doesn't look like it's our fault](https://github.com/python/cpython/pull/21473). If you change the FROM line in dockerfiles/web/Dockerfile to any of the pre-3.8 tags (3.7-buster, 3.6-buster, 3.5-buster) you should be able to successfully build and run.

I'll be PRing a fix for everyone else to benefit from too. Thanks for flagging the issue for us!

**Comment by rabble** [comment]
I tried out f6675899f4461a7b9bdde511502f37b7e9853161 but it doesn't work either, same error.

**Comment by r4v5** [comment]
@rabble that's a really interesting error, because that werkzeug issue shouldn't be present with the version specified in our requirements.txt and doesn't occur for me. Would you be willing to try again with [the code on this PR's branch](https://github.com/lucyparsons/OpenOversight/pull/757)? (the branch is `fix-754-broken-image-build`)

**Comment by rabble** [comment]
Well... different error on the fix-754-broken-image-build branch

`2020-07-17 16:42:39 (1.54 MB/s) - ‘geckodriver-v0.26.0-linux64.tar.gz’ saved [2390549/2390549]

Removing intermediate container 769420a0991a
 ---> 0ef96fc47385
Step 11/30 : RUN mkdir geckodriver
 ---> Running in e7375dbb3b56
Removing intermediate container e7375dbb3b56
 ---> 991b911d291f
Step 12/30 : RUN tar -xzf geckodriver-${GECKODRIVER_VERSION}-linux64.tar.gz -C geckodriver
 ---> Running in 98c956b09125
Removing intermediate container 98c956b09125
 ---> 685c25014aaf
Step 13/30 : RUN npm install -g yarn
 ---> Running in 3d43905f4179
/bin/sh: 1: npm: not found
ERROR: Service 'web' failed to build: The command '/bin/sh -c npm install -g yarn' returned a non-zero code: 127
make: *** [build] Error 1
 !  ~/c/p/OpenOversight   fix-754-broken-im…build $ `

**Comment by r4v5** [comment]
@rabble @jclr The issues you've reported should all be fixed in the latest commit of `develop`. Thank you for reporting them and bearing with us!
