### ISSUE TITLE
Users can't confirm their emails on staging

### ISSUE THREAD

**Issue by McEileen** [lucyparsons/OpenOversight#762]
While testing staging for bugs, I found a bug where users can't confirm their emails.

When the user clicks the link in their confirmation email and then logs in, it takes them to the `/auth/unconfirmed` page, which says  `You have not confirmed your account yet.`  However, this page also displays a flash message that says, 'You have confirmed your account. Thanks!'

I looked through the staging logs and found this error

```
Jul 19 19:48:02 staging gunicorn[30256]: Traceback (most recent call last):
Jul 19 19:48:02 staging gunicorn[30256]:   File "/home/nginx/oovirtenv/venv/lib/python3.5/site-packag
Jul 19 19:48:02 staging gunicorn[30256]:     self.handle_request(listener, req, client, addr)
......
Jul 19 19:48:02 staging gunicorn[30256]:   File "/home/nginx/oovirtenv/venv/OpenOversight/OpenOversig
Jul 19 19:48:02 staging gunicorn[30256]:     and request.endpoint[:5] != 'auth.' \
Jul 19 19:48:02 staging gunicorn[30256]: TypeError: 'NoneType' object is not subscriptable
```

I think this error comes from the method [`before_request()` ](https://github.com/lucyparsons/OpenOversight/blob/develop/OpenOversight/app/auth/views.py#L21)in `auth/views.py`.  `request.endpoint[:5]` will throw an error when `request.endpoint` is `None`.

I'll submit a PR with a fix.

**Comment by brianmwaters** [comment]
@r4v5 how come this got reopened? Looks like you had merged a PR by @McEileen that is supposed to have fixed this

**Comment by McEileen** [comment]
@brianmwaters Unfortunately, the PR I merged didn't fix the bug.  I'm still working on this issue.
