### ISSUE TITLE
The workaround hack I use at the moment is

### ISSUE THREAD

**Issue by am-i-the-rabbit** [lucyparsons/OpenOversight#764]
Whoops

I meant to add a lot more to this and fat fingered the enter key
Sorry guys

I ran into an issue with make dev that left me without the index.css file, and the below comment provided a fix, albeit crude.
I had to create the dist directory and chmod 33 the directory
But afterward, running make assets didn't work; I got a permissions error
Had to run sudo make assets and it worked beautifully

I guess this isn't so much an issue as curiosity about what's going on here? I'm new to this project and don't really have a complete understanding of all the inner workings yet. Please forgive my ignorance.

I'm concerned that future builds will produce a similar problem, even though it looks like the originally issue the below fix was offered for has been closed. And I'm pulling the latest develop repo, so I'm not sure why I'm still running into this?

Not asking for a crayon drawing or anything, just curious if I should expect any further errors and we move from dev to production?

Thanks!

QUOTED FROM ANOTHER COMMENT:

The workaround hack I use at the moment is

`mkdir OpenOversight/app/static/dist/`
`sudo chown 33 OpenOversight/app/static/dist/`

`make assets` and `make cleanassets` then work as expected.

There is a similar issue with the `container_data` folder created by postgres.

Maybe there is some way to fix this with user namespaces or something. I am not a docker expert by any means.

_Originally posted by @brianmwaters in https://github.com/lucyparsons/OpenOversight/issues/713#issuecomment-640117580_

**Comment by peculater** [comment]
Hi hi.  I did some work in #714 and #739 to help out with that problem.  On the latest develop version, a `make clean` and `make dev` should destroy and re-create the directory and index.css file with the right permissions.  You can run `make clean_all` if you're seeing problems with database file permissions too.

A short explanation is that when the python container runs, by default the user that starts the container is transformed to the root superuser (user 0) inside the container.  Outside the container where text editors are able to edit the application files, that user is known by their original ID (user 1000 for instance).  Trying to make sure that files written by one user ID are useful to the other ID in all cases is a hard problem.  #714 was about trying to make the user ID the same both inside and outside the container, to make this whole thing simpler.

On my machine at least, running `make assets` after that seems to work well.  Do you have a way to repeat the error you're seeing?  Like I said, this is a hard problem and I'd love to find where there are cases that this strategy fails.

**Comment by am-i-the-rabbit** [comment]
Hey! Thanks for the reply.

So, I used the `make assets` work around you suggest, and it did work. It fixed pretty much everything. No problems there.

As far as getting it to repeat the same thing, I can try. But I'm not sure. I do appreciate the breakdown of the what causes it, though. That sounds pretty close to what was happening. I did have to `make clean_all` (database and all).

Is this why I have to `export UID` per the docker-compose.yaml file? That was one of the first issues I ran into but that was pretty self explanatory. I assume that's one of the things applied to fix this particular problem?

I'll see what I can do about replicating this. Maybe I'll get lucky. Hah!

Thanks!

**Comment by peculater** [comment]
Glad to hear the `make` commands worked for you! :-)

You're exactly correct, the `export UID` is so that the processes inside the container know what UID is expected of them when they're writing files that are shared outside of the container.  The Makefile and `make` commands do that for you automatically but if you're using `docker-compose` directly that's what it's looking for.

Please do let us know if there are other stumbling blocks.  A good dev experience makes every other change easier.

**Comment by am-i-the-rabbit** [comment]
Absolutely. And I'm happy to contribute any way I can. We have a solid group of people working on this together and I hope we can provide as much backup for you guys as possible.

I'm going to leave this issue open just until I find out if I can replicate that error. If not, I'm just gonna call it a fluke and close this. But understanding why it happened was the big thing, and I understand now.

Thank you!

**Comment by am-i-the-rabbit** [comment]
So, I've tried off and on--to no avail--to replicate this. I'm going to guess it was a fluke occurrence that happened because I had run `make dev` a bunch of times and got some stuff scrambled in the process. If I run across it again, I'll reopen this issue and we can work from there, but I'm not going to close this for now.

Thanks for your help, @peculater!
