### ISSUE TITLE
What if an officer works at multiple departments?

### ISSUE THREAD

**Issue by am-i-the-rabbit** [lucyparsons/OpenOversight#765]
We have a handful of data in csv files that we're getting ready to upload into our OpenOversight environment. A lot of these officers happen to be currently active in multiple department. Would there be any way to reference multiple departments from a single officer's profile? This might be obvious but, again... n00b. :-)

If this isn't possible, does anyone have a similar situation that you've managed to build a work around for?

Thanks!

**Comment by brianmwaters** [comment]
Hey @am-i-the-rabbit, I'm working on uploading a bunch of Vermont departments into OO, and we have the same thing for one or two cops. Currently, the bulk import scripts don't have a way of handling this, so after we run our bulk import, each of those cops will have multiple profiles, one for each department. For us, it's only one or two, so we may merge them by hand afterwards. If, in your case, it's a lot, then we might have to come up with a good solution, which could involve extending the bulk import scripts.

**Comment by abandoned-prototype** [comment]
I don't think the database supports multiple departments for one cop either. I don't know how common this is in general, so for now I don't think it's worth the complications that come with it to make it a many-to-many relationship. My suggestion for now would be to have a profile for the cop in each department and add a link (like an actual hyperlink) to the profile of each pointing to the other to allow for some kind of continuity.

One way to relatively quickly represent multiple departments would be to add the department_id to the assignment model, then one cop could have multiple assignments with different departments, but that might come with its own set of complications

**Comment by brianmwaters** [comment]
> I don't think the database supports multiple departments for one cop either.

Oh, oops, I was running on the incorrect assumption that the `department_id` field was in the `assignments` table, not the `officers` table. I checked and you are right unfortunately.

I agree that putting links in profiles by hand is a good idea.

**Comment by am-i-the-rabbit** [comment]
That's what I was afraid of. It's not a terrible issue, though. We can work around it for the time being. Depending on how common this is, and how many other people report the issue, maybe we could look into including this functionality in a future build, but I'm not going to sweat too much over it tonight.

And, since you mention bulk uploads... did you guys need to do anything special to run `flask bulk-add-officer myfile.csv` or were you able to run it without modifications?

I'm trying to use a sample set of ten or twelve records to test this but I keep getting "Missing required field". The traceback is in the screenshot below, if that helps. Am I doing something wrong? This might need to be created as a separate issue but I'm doing my best not to spam the issues for this repo. XD

![image](https://user-images.githubusercontent.com/64817895/88253043-53143400-cc7e-11ea-8699-3ea691bdb5a2.png)

**Comment by abandoned-prototype** [comment]
Is the header line you posted verbatim? csv files are whitespace sensitive, so if `department_id, first_name, last_name, job_title, star_no, unique_internal_identifier` is the header line it will be unpacked as `row[" first_name"]` instead of `row["first_name"]`. We should potentially just add a `strip()` to not make it an issue.
Also if you haven't seen it there is some documentation at https://github.com/lucyparsons/OpenOversight/blob/develop/docs/bulk_upload.rst

**Comment by abandoned-prototype** [comment]
Also definitely feel free to open more issues if things are not directly related. There is a good chance that others run into similar problems

**Comment by am-i-the-rabbit** [comment]
Thank you! That was it.
I don't work with CSV files much. Totally missed that. This is why I love dev communities. :-)
