### ISSUE TITLE
deployment for production

### ISSUE THREAD

**Issue by am-i-the-rabbit** [lucyparsons/OpenOversight#766]
Hello, again, everyone. You guys are going to get so bored with my issues. lol

I'm actually hoping that maybe we can mitigate that by separating dev issues from deployment and admin issues. I love this project, and I plan to be working on/with it for a long time. And I'm already a python geek.... that parrot's already dead.

Anyway, I'm working on deploying a production environment right now, and I have--thank gods--not run into any serious problems yet. But I do have some questions about bulk uploads, managing the database, etc., that are going to be less "issues" and more just FAQs and admin stuff. Would anyone be willing to connect with me in a DM or via e-mail to help us out with that?

I'll be switching gears back to dev once we've got the production environment up and running, at which point I will be back here to bother everyone with dev questions and new bizarre-o stuff in testing.

Anyway, thanks in advance for anyone willing to connect with us. And thanks again for all the help this community's already supplied in getting us this far. Hope everyone's Friday is off to a good start!

**Comment by am-i-the-rabbit** [comment]
Scratch that. We got where we need to be; found the missing piece, so to speak.

**Comment by brianmwaters** [comment]
@am-i-the-rabbit looks like you're building out a production instance of OpenOversight. That's great! You're also welcome to add your local department to the main OpenOversight instance at openoversight.com. I don't think twitter supports DM's, but you can email me at the email I use in my commits, or at info@lucyparsonslabs.com.

**Comment by am-i-the-rabbit** [comment]
Hey Brian,

I actually e-mailed you guys just the other day. Francis replied and I believe you were one of two people he CC'd that.

We are building out to production, so I will absolutely take notes and send as much feedback your way as possible.

Thank you!
