### ISSUE TITLE
bulk-add-officers breaks department browsing; "object has no element 0"

### ISSUE THREAD

**Issue by am-i-the-rabbit** [lucyparsons/OpenOversight#768]
So, I've got a massive csv file I was going to put up. And I tested this with a few different *small* sets of data but something is going on when I try `flask bulk-add-officers cops.csv`. From bash, it seems to be fine. I see line after line of officers successfully added.

I created a new department for them, and made sure department_id for each officer in the csv is 3, to match the id in the departments table, and ensured that there is a first_name, last_name, job_role, and star_no and/or unique_internal_id for each. so in theory, i should have all the right data for minimum required info, to upload all these officers.

Then when I go to the webapp and try to browse the officers for this new department I've created, I find that I've apparently angered the gods:

```
File "/usr/local/lib/python3.5/site-packages/jinja2/_compat.py", line 28, in reraise
raise value.with_traceback(tb)
File "/usr/src/app/OpenOversight/app/templates/list_officer.html", line 2, in top-level template code
{% import "bootstrap/wtf.html" as wtf %}
 
{% block content %}
<div class="container" role="main">
  <h1>{{ department.name|title }} Officers</h1>
  <div class="row">
File "/usr/src/app/OpenOversight/app/templates/base.html", line 97, in top-level template code
      </div>
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
    {% block content %}{% endblock %}
Open an interactive python shell in this frameOpen an interactive python shell in this frame 
    <footer class="footer">
      <hr>
      <div class="row text-center horizontal-padding">
 
File "/usr/src/app/OpenOversight/app/templates/list_officer.html", line 139, in block "content"
        {% if officer.face.first() is none %}
            {% set officer_image = '/static/images/placeholder.png' %}
          {% else %}
            {% set officer_image = officer.face.first().image.filepath %}
          {% endif %}
        {% set assignment = officer.assignments.order_by(officer.assignments[0].__table__.c.star_date.desc()).first() %}
        <li class="list-group-item">
            <div class="row">
              <div class="col-md-6 col-xs-12">
                <img src="{{ officer_image }}" class="img-responsive thumbnail" alt="{% include 'partials/officer_name.html' %}">
              </div>
File "/usr/local/lib/python3.5/site-packages/jinja2/environment.py", line 475, in getattr
return obj[attribute]
jinja2.exceptions.UndefinedError: sqlalchemy.orm.dynamic.AppenderBaseQuery object has no element 0
```

So my first thought is that I've seen this before and I want to say it had to do with either a database join type or an object missing a value in a required field? Maybe? But if it had anything to do with the database joins wouldn't I get this same error loading one of the test departments? They seem to load up fine.

I checked for the "object has no element 0" in these issues but didn't see anything about it. Has anyone else seen this? How'd you get passed it?

The thought also crossed my mind that maybe I should try uploading more details to create more unique records but I don't think that should make much difference as long as the req'd fields are satisfied?

**Comment by abandoned-prototype** [comment]
I thought I had seen this problem and a fix before, but I guess not. What I think the issue is, is that the template expects every officer to have an assignment  (see the part `officer.assignments[0]`), but the bulk upload didn't create any assignments because those fields weren't present in the csv.
This is part of a more general problem that our templates and other parts of the code make implicit assumptions on the data that are not enforced on a database level or documented anywhere.

For a quick fix in your situation, adding a field `job_title` to the csv with the value "Not Sure" might "solve" this issue (I did not test this however)

**Comment by am-i-the-rabbit** [comment]
Alrighty. I forgot to close this earlier but I got it resolved.
I actually did two things, and I'm not exactly sure which fixed this:

I resaved the CSV file with our data for upload with *nix-formatted CRLF. It appeared to be reading the file as a single, long line which... obviously... didn't...work. XD

But I don't think that's what fixed this error, after thinking about it a little bit. The other thing I did was add some additional fields to populate, the important one being the unique internal identifier. I realized a bit later that not all of the people in our source file are uniformed, so not all of them will have a badge id (star_no). When I was parsing the CSV from JSON source, I didn't bother pulling and including the UII# thinking we wouldn't need it.

I was wrong. lmao
Since some of the employees in our list weren't officers, we were trying to upload a file that had some records in it that couldn't be guaranteed unique without star_no or unique_internal_identifier. Soon as I added that to the CSV (and after changing the CRLF formatting), I was able to upload without much trouble.

Thanks for making the suggestion to check those fields, @abandoned-prototype .

**Comment by brianmwaters** [comment]
> For a quick fix in your situation, adding a field `job_title` to the csv with the value "Not Sure" might "solve" this issue (I did not test this however)

Alternatively, it would be cool to fix the templates so they don't do this! I actually made a few changes like that in the Vermont pull request. Having an officer w/o any assignments seems totally reasonable - it just means we don't know their rank.

**Comment by am-i-the-rabbit** [comment]
So, we get our data in JSON format, and i have to parse it to CSV to be uploaded, anyway. So I built a little python script and set a list variable containing all the actual ranks. Then there's a condition for each parsed record that if the data from the job_title field in the JSON source isn't in that list, it sets the rank to "Not Sure" and continues on.

Similarly, if either badge number or employee id aren't available in our source, I have it set to use an empty string as opposed to the default "None" when either of these fields have no value. Since None isn't a string, it causes an error when trying to write a non-string value into a string....

I've been toying around with the idea of building a web form to upload the JSON file, then feeding it through a beefed up version of the script I've got, then sending it through bulk-add-officers. I'm still trying to decide whether or not it's worth the effort.

**Comment by brianmwaters** [comment]
re: the issue w/ `None` vs `""`, see this issue: https://github.com/lucyparsons/OpenOversight/issues/711

**Comment by abandoned-prototype** [comment]
Personally I think the way that @brianmwaters/Vermont went in that regard is the best approach right now: Keep all the scripts you are using to transform the data and publish them in your own repo. That way,  it's possible to reproduce where the data is coming from and other people can learn and adapt those for their own needs, but nobody expects them to automatically also work on their data (and unfortunately pretty much every department has a different way of providing data and includes different attributes, etc.)
