### ISSUE TITLE
Photo Upload Bug Stacktrace

### ISSUE THREAD

**Issue by fritzdavenport** [lucyparsons/OpenOversight#774]
Could just be in dev with werkzeug, but could be confusing if it also exists in prod and there's ever an issue. Stack traces bleed into the UI when there's an upload error. Frontend errors could/should probably alert the user that an error occurred but send the trace to a database table or some other log aggregation.

![Screenshot from 2020-07-27 16-14-07](https://user-images.githubusercontent.com/5983782/88613421-6860d800-d05b-11ea-9dde-a840931d7292.png)

**Comment by fritzdavenport** [comment]
Additionally - if there's a 404 on profile pictures - photos are just empty gray boxes, with no indication of the failure to load

**Comment by brianmwaters** [comment]
From the screenshot, this looks like markup to me. Is there also a stack trace? In any case, do you have a URL or similar to reproduce?

**Comment by fritzdavenport** [comment]
@brianmwaters - yea, looks like an html render of a stack trace, you can see the `botocore.vendored.requests.exceptions.ConnectionError: ("Connection aborted.', OSError(...` in the second line of the HTML. The line after implies that it's a Werkzeug render (which makes sense, I'm running Flask via Werkzeug locally) 

I don't know if it'd manifest in production, and I specifically triggered it because of some of my own broken code that had since been fixed

**Comment by brianmwaters** [comment]
Oh, this is probably triggering because your local dev instance isn't setup to work with S3.

I think that it's safe to assume that if you can dump a stack trace on your local dev instance, than it could be dumped on prod if there were some issue w/ S3. So this is probably a legit bug that should be fixed!

**Comment by brianmwaters** [comment]
@abandoned-prototype said on slack that we have a debug flag which is set on local dev instances and not in prod. @fritzdavenport can you see if you can still reproduce this w/ the debug flag unset? If not, this isn't a bug, but if you can, then it is.

**Comment by fritzdavenport** [comment]
Confirmed in slack that bug is not present in staging, closing.
![Screenshot from 2020-07-27 23-34-44](https://user-images.githubusercontent.com/5983782/88616997-93e7c080-d063-11ea-81c5-9f955c7f19b1.png)

**Comment by fritzdavenport** [comment]
gg
