### ISSUE TITLE
500 on image upload shows confusing error message

### ISSUE THREAD

**Issue by McEileen** [lucyparsons/OpenOversight#776]
If a 500 occurs when a user attempts to upload an image, the user will see the raw text associated with the 500.  It would be good to display something more user-friendly.

h/t to @r4v5 for pointing this out

**Comment by bmwasaru** [comment]
Would something like this work?
![Screenshot 2021-04-27 at 13 18 42](https://user-images.githubusercontent.com/1927073/116230328-2e467300-a760-11eb-9a26-6c4af0266025.png)

**Comment by brianmwaters** [comment]
I think that would be great, definitely an improvement.

**Comment by abandoned-prototype** [comment]
Fixed in https://github.com/lucyparsons/OpenOversight/commit/c7bb5dd989518eb7210573d006b2069b67609209
