### ISSUE TITLE
Confirmation links in e-mail don't work

### ISSUE THREAD

**Issue by am-i-the-rabbit** [lucyparsons/OpenOversight#782]
It looks like the links being sent to users for confirmation aren't working. I've tested this with a few different test accounts. The user registers. I get a "please approve" message. So I approve (and I've tried doing it from both the e-mail and the web  app) and the user gets their "please confirm" message. They click the message, but it doesn't approve the account. Instead, it makes no changes to the users table but still spits out another message to the admin saying confirmation was successful. 

If the user tries to login, then, they get an error that their account is still pending admin approval. if I do `select * from users where email = <users email>;` from in psql, the user's approved attribute is still true and confirmed is still false. I can manually set confirmed to true and the user can log in, no problem.

I'll have more time later this afternoon to work on this and I can see if gunicorn recorded anything, then.

**Comment by am-i-the-rabbit** [comment]
Wait. It looks like this might be related to #762 and may even be the same issue. I'll look more into that first when I get back to this.

**Comment by r4v5** [comment]
@am-i-the-rabbit Hi! I think I have a fix for this in latest develop. Please let me know if it fixes it for you too :)
