### ISSUE TITLE
Organization of department listing

### ISSUE THREAD

**Issue by fritzdavenport** [lucyparsons/OpenOversight#792]
Looking at openoversight.com, I wonder if there should be general bounding boxes or overall categories for departments? I see a few departments for VT, but I can't imagine it'd be clear to a non-Vermont resident what "Colchester PD" is, and where that is specifically. 

Would states make sense to group departments? Not sure why CBP would fit in that

**Comment by redshiftzero** [comment]
see #364 where there was a suggestion to have a map for selecting the department

**Comment by fritzdavenport** [comment]
closing as dupe, thanks @redshiftzero
