### ISSUE TITLE
Chicago PD's browse page 500s on both prod and staging

### ISSUE THREAD

**Issue by McEileen** [lucyparsons/OpenOversight#793]
When I navigate to the "browse department" page for the Chicago Police Department, there is a 500 on both prod and staging.

When I looked at logs in staging, I saw this

```
$:   File "/home/nginx/oovirtenv/venv/OpenOversight/OpenOversight/app/templates/list_officer.html", line 141, in block "content"
$:     {% set star_no = "#" + assignment.star_no %}
$: TypeError: Can't convert 'NoneType' object to str implicitly
```

I only see this bug for the Chicago Police Department.  My initial theory is that something get messed up with the migrations for Chicago, and the assignments are missing from the database.

**Comment by redshiftzero** [comment]
still seeing internal server error on staging, reopening

**Comment by redshiftzero** [comment]
I have applied the hotfix in #796 to staging and production to resolve this 500, we should obviously still merge
