### ISSUE TITLE
Filter by photo availability

### ISSUE THREAD

**Issue by todrobbins** [lucyparsons/OpenOversight#798]
I noticed that it would be really useful as a user to filter by the presence or absence of a photo. Something like:

**Photo**
- [x] Available
- [ ] Not Available

**Comment by michplunkett** [comment]
It's a bit late, but we're finally gonna start implementing this today, @todrobbins. Thanks for creating the issue!

**Comment by michplunkett** [comment]
This is being worked on now, @todrobbins.

**Comment by michplunkett** [comment]
Here's the PR, @todrobbins: https://github.com/lucyparsons/OpenOversight/pull/965
