### ISSUE TITLE
Database creation/Installation question

### ISSUE THREAD

**Issue by JoshuaOpolko** [lucyparsons/OpenOversight#83]
According to OpenOversight/database/readme.md the database can be created by running the script at OpenOversight/createdb.py. This script doesn't appear to exist at this location. I've run the one at OpenOversight/OpenOversight/createdb.py but it appears to expect an environmental variable PGPASS. I'm assuming there should be a initial script that reads the .pgpass file and sets the variable so it feels like a file may be missing at OpenOversight/createdb.py. Please advise. Thanks.

**Comment by freddymartinez9** [comment]
@JoshuaOpolko when we added Vagrant and refactored the Postgres DB, we changed the way you can connect to the db. You should be looking at [CONTRIB.md](https://github.com/lucyparsons/OpenOversight/blob/develop/CONTRIB.md) which is how we define the RDS we are connecting to.

**Comment by r4v5** [comment]
We'll be changing this again slightly once I JFDI it, moving to defining the params in a .env file in the project directory instead of having you shove things into the global environment, but you're correct that our documentation wasn't right. Freddy fixed the docs a bit, and I'll take another stab and updating and harmonizing CONTRIB.md and DEPLOY.md a bit better when the new change happens.

**Comment by r4v5** [comment]
I've updated the documentation in #87 for the New Way of Doing Things. If you could look it over and let me know if it makes sense to someone who isn't intimately familiar with the project's internals, it would be appreciated, @JoshuaOpolko.

**Comment by JoshuaOpolko** [comment]
Thank you  @r4v5 I'll take notes as I go, maybe I can help put together a guide for new users like myself.

**Comment by JoshuaOpolko** [comment]
I'm following the instructions in the CONTRIB.md file, I installed vagrant & librarian-puppet from apt. When i execute "rake vagrant:provision" the message appears "vagrant up - No usable default provider could be found for your system. Vagrant relies on interactions with 3rd party systems, known as "providers"..."  I'll read up on vagrant, it seems to require configuration for a 3rd party provider before it comes up enough to SSH into.

**Comment by r4v5** [comment]
Provider in this case is Vagrant's word for "vm subsystem"; is it not finding VirtualBox? You shouldn't need to `apt-get install librarian-puppet`, it'll be installed by bundler.

**Comment by JoshuaOpolko** [comment]
No it doesn't seem to be finding any vm to connect to. I just the instructions for setting up a systemd entry refer to "/home/nginx/oovirtenv/..." I don't have that folder. I think I've missed a big piece that probably installed a virtual machine locally. I didn't see that listed anywhere though. Also I had to update the first line of forms.py to say "from flask_wtf import Form as Form" before gunicorn would start. Maybe it's my version of flask though, I'm going to start another install on a clean system and see if the bundler will install everything for me this time and if there's a virtualbox installation piece i missed.

**Comment by r4v5** [comment]
REAL quick question: you trying to get this set up in production or as a test/dev machine? My advice has been for dev machines.
Dev machines currently require you to have Vagrant and VirtualBox installed already (it's Oracle, I know, but it's free-as-in-beer and cross-platform). `vagrant up` starts VirtualBox, which does the actual building of the VM, and maps port 3000 on the VM to 3000 on localhost. It's a kinda weird gloves-in-an-isolation-booth approach, but it's generally easier for us to support one standard VM configuration than making it work for people who want to develop on different linux distros and macos and windows.

**Comment by JoshuaOpolko** [comment]
Yeah I'm liking the idea of vm's and docker/etc for consistency/simplicity more and more. I'm really just looking to get a local copy of the db running so i can work on item #76. I can create my own dummy db just to get it working though, just at some time will have to add the specific table/columns/etc from the OO db. My purposes are development right now, but whichever setup lets me access a copy of the db would be great.

**Comment by r4v5** [comment]
If you `git checkout vagrant-update`, and install virtualbox, provisioning should plop a postgres DB into your filesystem and populate it with test data.

**Comment by JoshuaOpolko** [comment]
I started a new install on a Ubuntu 16.04.1 VPS. All instructions completed successfully until "rake vagrant:provision" when message appears: 

**[Librarian] Install: dependencies resolved
[Librarian] Installing puppetlabs-stdlib/4.12.0 <https://forgeapi.puppetlabs.com>
Unable to load puppet. Please install it using native packages for your platform (eg .deb, .rpm, .dmg, etc).
puppet --version returned pid 12365 exit 1**

When I execute 'bundle install' displays the following puppet packages 'in use'
**Using puppet_forge 2.2.2
Using librarian-puppet 2.2.3**

Are there any other puppet packages that should be installed? I'd like to try installing them through apt to test if poss.

Also /OpenOversight/vagrant/puppet/modules is empty, should there be modules here?

**Comment by redshiftzero** [comment]
Hey @JoshuaOpolko, did following the instructions now in `CONTRIB.md` under "Development Environment" fix this for you?

**Comment by JoshuaOpolko** [comment]
I've run through it again, the steps completed much farther but it hangs indefinitely at vm boot with the following:

==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...

It remains there, if I attempt to ssh in from another terminal message displays "VM must be created before running this command. Run `vagrant up` first." I've tried stopping/restarting/reboot it continues to hang at this stage. I'll read up on it a bit and then try from  a fresh VPS again. Maybe the steps i did last time are part of the conflict now.

**Comment by freddymartinez9** [comment]
assigning to @r4v5

**Comment by JoshuaOpolko** [comment]
Reinstalled on a pristine VPS, the install was smooth except puppet was not installed by script so i installed it with apt. After this 'rake vagrant:provision' command generated some [Librarian] event successfully until failing with 'vagrant up' followed by 'rake aborted!' Command failed with status (127): [vagrant up...]'

**Comment by freddymartinez9** [comment]
Hang on, `vagrant up` is for a local development environment for testing changes but the staging.oo.lpl is different. you shouldn't try to run this on a new VPS, that actually doesn't matter. Can you not run this locally with VirtualBox install ?

**Comment by JoshuaOpolko** [comment]
I'm installing OpenOversight on my laptop. My steps are below:

Good
1. git clone https://github.com/lucyparsons/OpenOversight
2. cd OpenOversight
3. python setup.py build/install
4. gem install bundler *I believe the puppet install failed so i installed it from apt.
5. bundle install -> ok 2 gemfile dependencies, 21 gems now installed

Issue
6. rake vagrant:provision -> displays the following:

[Librarian] Install: dependencies resolved
[Librarian] Installing puppetlabs-stdlib/4.12.0 <https://forgeapi.puppetlabs.com>
[Librarian] Installing puppetlabs-apt/2.3.0 <https://forgeapi.puppetlabs.com>
[Librarian] Installing puppetlabs-concat/2.2.0 <https://forgeapi.puppetlabs.com>
[Librarian] Installing puppetlabs-postgresql/4.8.0 <https://forgeapi.puppetlabs.com>
[Librarian] Installing stahnma-epel/1.2.2 <https://forgeapi.puppetlabs.com>
[Librarian] Installing stankevich-python/1.17.0 <https://forgeapi.puppetlabs.com>
vagrant up
rake aborted!

Besides puppet i also installed virtualbox from apt by hand. Any suggestions are appreciated!

**Comment by JoshuaOpolko** [comment]
It's looking very good after help from @r4v5 . I'd forgotted to install vagrant on the laptop , after this an image was succesfully downloaded and launched via vagrant. I can ssh in and see the db so this issue can be closed. Thanks.

**Comment by JoshuaOpolko** [comment]
To access the db within vagrant from the host machine the following files were modified:
Vagrantfile:
config.vm.network "forwarded_port", guest: 5432, host: 5433
pg_hba.conf:
host  all  all 0.0.0.0/0 md5

**Comment by r4v5** [comment]
I can update the puppet provisioner to add that ACL entry if it's helpful for you. In retrospect, I probably should have already.

**Comment by JoshuaOpolko** [comment]
Appreciate that when it' time, but I'm not crazy about it being left open to any IP. I'd imagine it should be set to specific hosts at some point.

**Comment by r4v5** [comment]
Actually when I think about it, I believe the port forwarding makes things appear from localhost. I'll dig into it more when I have some Copious Free Time in the next week.

**Comment by redshiftzero** [comment]
Hmm, was this resolved?

**Comment by redshiftzero** [comment]
Closing for now, let's file a followup more specific ticket if there's more to be done here.
