### ISSUE TITLE
Add how-to on contributing anonymously to CONTRIB.md

### ISSUE THREAD

**Issue by abandoned-prototype** [lucyparsons/OpenOversight#837]
When people open a PR or respond to issues their github profile is associated with this project. Additionally, git itself adds meta-data to every commit, that contains an email-address and name stored locally. Not everyone is comfortable having their real name publicly associated with this project, and everyone contributing should know the information they share.
So we should add some instructions to the CONTRIB.md file. This should at least contain information or links on how to change the name & email associated with a commit, and how to find that @github email that makes commits be associated with your account, without having to publicly disclose your github-email. Probably also add a disclaimer that this doesn't guarantee anonymity

**Comment by r4v5** [comment]
I'd also say part of the scope of this would be to update our [pull request template](https://github.com/lucyparsons/OpenOversight/blob/develop/PULL_REQUEST_TEMPLATE.md) with either a link to the info or a tl;dr summary for people.
