### ISSUE TITLE
Incidents can be linked to officers that don't belong to the incident department

### ISSUE THREAD

**Issue by McEileen** [lucyparsons/OpenOversight#839]
Desired outcome:
- If a user attempts to create an incident for a department, and then selects officers from another department as being involved in that incident, the user will see an error message

Current outcome:
- If a user attempts to create an incident for a department, and then selects officers from another department as being involved in that incident, the incident is created and persisted to the database 

Steps to reproduce:
1) Log in as admin and navigate to `/incidents`
2) Create an incident
3) Choose a department for the incident
4) Select officers that don't work for that department, and link them to the incident

Relevant areas of the codebase: 
- `IncidentForm` in `main/forms.py`
- `IncidentApi` in `main/views.py`

**Comment by Spraynard** [comment]
Currently working on this issue

**Comment by Spraynard** [comment]
Closed PR because it was consensus that, in reality, another department's officers can be part of an incident and it doesn't make sense to limit
