### ISSUE TITLE
Enable uploading of .webp

### ISSUE THREAD

**Issue by brianmwaters** [lucyparsons/OpenOversight#844]
This is an increasingly common image file format that we should allow. We whitelist file extensions in a configuration file somewhere, so it should be a simple one-line fix to add .webp.

**Comment by abandoned-prototype** [comment]
Hi @brianmwaters. Thanks for https://github.com/lucyparsons/OpenOversight/pull/845. I tested this on staging and found that we still need a small change on the javascript tool we use for the upload. I made that change here: https://github.com/lucyparsons/OpenOversight/pull/848. All other functionality I tested works
