### ISSUE TITLE
Leaving overtime field blank when adding a new officer causes an error

### ISSUE THREAD

**Issue by brianmwaters** [lucyparsons/OpenOversight#856]
When adding an officer using the form at https://openoversight.com/officer/new, if the "OVERTIME PAY" field is left blank, then after the form is submitted, the user sees an error that reads "Not a valid decimal value" (see screenshot).

![image](https://user-images.githubusercontent.com/12619481/106088660-5f2cf280-60f4-11eb-9ff8-4a14a14b59db.png)

The desired behavior should be, that if the OT field is left blank, then the app assumes that OT pay was $0 or unknown, and proceeds without error.

**Comment by Spraynard** [comment]
Still exists. @abandoned-prototype would you be able to add me as assignee on this one?

**Comment by Spraynard** [comment]
@michplunkett This should have been fixed & could be closed

**Comment by michplunkett** [comment]
Fixed via this PR: https://github.com/lucyparsons/OpenOversight/pull/1083
