### ISSUE TITLE
404 error on Securedrop link in footer 

### ISSUE THREAD

**Issue by erinburns** [lucyparsons/OpenOversight#890]
The Securedrop link in the footer on the [OpenOversight page](https://openoversight.lucyparsonslabs.com/) goes to this [page](https://lucyparsonslabs.com/securedrop/) which displays a 404 not found error and the following information:
Code: NoSuchKey
Message: The specified key does not exist.
Key: securedrop/index.html
RequestId: HVK4ASE125KW3W60
HostId: rdbBzQuFDOMRcpNXHqh3vyjK9E2FJvORd+U4cwlIklSk4OfbF9EwPvUyE4pcLsB5OB6PGdS4sYI=

**Comment by abandoned-prototype** [comment]
Thanks for the report!
This is addressed in https://github.com/lucyparsons/OpenOversight/commit/6f50d6944b0139ba8b3a307b31cef40de55b5c02, we are removing the reference since the linked Securedrop is no longer maintained
