### ISSUE TITLE
Disabling a user doesn't do anything

### ISSUE THREAD

**Issue by sea-kelp** [lucyparsons/OpenOversight#892]
Hello! I help out with the Seattle-area [OpenOversight fork](https://github.com/OrcaCollective/OpenOversight) and just wanted to make sure you're aware of a bug we found in our fork:

> Currently when "Disabled?" is checked for a user, it doesn't actually have any effect. The user can still log in and do everything an active user can do.

Feel free to pull in our fix from this PR: https://github.com/OrcaCollective/OpenOversight/pull/192

**Comment by AetherUnbound** [comment]
I should note that it seems that "disabling" the user prevents them from performing the "Image classification" or "Officer identification" tasks accessible through the "Volunteer" tab! 
![image](https://user-images.githubusercontent.com/10214785/188258528-d0717026-8695-4981-94ce-ea5dd19ccf27.png)

**Comment by sea-kelp** [comment]
Thanks for pointing that out! :facepalm:
