### ISSUE TITLE
`APPROVE_REGISTRATIONS` flag does not appear to be working

### ISSUE THREAD

**Issue by michplunkett** [lucyparsons/OpenOversight#957]
## What issue are you seeing?
The `APPROVE_REGISTRATIONS` flag does not seem to be setting in docker, so I cannot correctly test the `AdministratorApprovalEmail`.

**Comment by abandoned-prototype** [comment]
It looks like, running `APPROVE_REGISTRATIONS=true make start` works for me. At least I am seeing a log for the admin approval email after registering a new account. Can you share more details of your current setup if that doesn't work?
