### ISSUE TITLE
Remove `H021` from `pre-commit` ignore list and make CSS classes/IDs

### ISSUE THREAD

**Issue by michplunkett** [lucyparsons/OpenOversight#969]
## Related Issue(s):
https://github.com/lucyparsons/OpenOversight/issues/239

## What issue are you seeing?
We currently have A LOT of inline styles and they will take some care to fix. This will be a good first issue for someone to contribute to the repository and would help us get our HTML in fantastic shape.

## Steps
1. Remove `H021` from the `ignore` list in the `.pre-commit-config.yaml` file.
<img width="357" alt="Screenshot 2023-07-12 at 12 59 00 PM" src="https://github.com/lucyparsons/OpenOversight/assets/5885605/3c37f17c-7aa6-44d0-b2e0-27faa39ccc78">

2. Make the necessary changes.

**Comment by michplunkett** [comment]
You'll be modifying the file `/OpenOversight/app/static/css/openoversight.css`.

**Comment by brrusselburg** [comment]
@artemisia-cana I can grab this, but don't wanna step on toes!

**Comment by michplunkett** [comment]
There are a handful of these, @brrusselburg, you can grab this if you want.
