### ISSUE TITLE
Remove `H013` from `pre-commit` ignore list and add alt tags to images

### ISSUE THREAD

**Issue by michplunkett** [lucyparsons/OpenOversight#970]
## Related Issue(s):
https://github.com/lucyparsons/OpenOversight/issues/239

## What issue are you seeing?
This error needs to be addressed in the HTML linting process: `Img tag should have an alt attribute.`

## Steps
1. Remove `H013` from the `ignore` list in the `.pre-commit-config.yaml` file.
<img width="377" alt="Screenshot 2023-07-12 at 1 22 34 PM" src="https://github.com/lucyparsons/OpenOversight/assets/5885605/79088ab1-0471-413b-bc1f-bb8fad803d3c">

2. Make the necessary changes.

**Comment by brrusselburg** [comment]
Happy to grab this one as well. Do we have alt text already made somewhere? If not, are we looking for anything specific with the descs (formatting, etc)?

**Comment by michplunkett** [comment]
We don't currently have the alternative text. :/ Outside of the alternative text being in present tense and concise, we don't have any hard rules.

Feel free to grab this one as well, but if we'd def prefer if you could submit the two in different PRs. In the PR for this, we'd also appreciate a small blurb in the `CONTRIB` document about how you thought through these. I'd be happy to help with that appendage to the document if you would like some help.
