### ISSUE TITLE
Create a help email account in the LPL GSuite

### ISSUE THREAD

**Issue by michplunkett** [lucyparsons/OpenOversight#972]
## What issue are you seeing?
We are currently using `info@lucyparsonslabs.com` as our help email address, but that should be changed to something that's just for helping users.

## Steps
- [x] Create email address
- [x] Create a PR to update the  `OO_HELP_EMAIL` variable value in [`docker-compose.yml` file](https://github.com/lucyparsons/OpenOversight/blob/7be3e2f35c85deccd7f73b1ff040d1929142417a/docker-compose.yml) and the production `.env` file.

**Comment by michplunkett** [comment]
Related to this PR: https://github.com/lucyparsons/OpenOversight/pull/971

**Comment by b-meson** [comment]
I think this was not an email address but a distribution group? (Different concepts in Gmail even though sometimes it uses the word "user" interchangeably".

**Comment by michplunkett** [comment]
I'll need an address that it maps to so that users can send questions, should they have them. However that works in Gmail is fine with me.
