### ISSUE TITLE
Write generic bash command for `Makefile` for creating an empty file

### ISSUE THREAD

**Issue by michplunkett** [lucyparsons/OpenOversight#973]
## What issue are you seeing?
We currently have some duplicated code in the `Makefile`. It'd be great to have that be one command where we pass it the file name instead of writing the same code down twice with a different file name each time.

Code snippet:
https://github.com/lucyparsons/OpenOversight/blob/eb84c13114155bcdaf8b6c89416f45b67e44f3c6/Makefile#L92-L105

**Comment by michplunkett** [comment]
https://stackoverflow.com/a/2826069

**Comment by abandoned-prototype** [comment]
Do we need the `create_empty_env` make command? Based on my understanding, the `.env` file is only used in prod where an empty `.env` file isn't really helpful I think

**Comment by michplunkett** [comment]
I BELIEVE it was needed for the tests to pass, but I could verify that tomorrow.

**Comment by michplunkett** [comment]
In the meantime, it'd be fine to take on this issue last.

**Comment by michplunkett** [comment]
It appears that we do not actually need this command, so this issue will be wrapped up once #1014 is merged.
