### ISSUE TITLE
Faces are squished 

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#98]
I just noticed that a bunch of our faces get kinda squished in the gallery view and it's hard for humans to recognize faces when distorted... If a frontend person wants to rock up in here and fix that I would be very happy

**Comment by freddymartinez9** [comment]
I believe this is controlled by this line in `app/static/css/bootstrap.css`, although someone should with CSS knowledge would know more
```
.img-thumbnail {
  padding: 4px;
  line-height: 1.42857143;
  background-color: #2b3e50;
  border: 1px solid #dddddd;
  border-radius: 0;
  -webkit-transition: all 0.2s ease-in-out;
  -o-transition: all 0.2s ease-in-out;
  transition: all 0.2s ease-in-out;
  display: inline-block;
  max-width: 100%;
  height: auto;
}
```

**Comment by freddymartinez9** [comment]
<img width="404" alt="screen shot 2016-12-19 at 14 26 41" src="https://cloud.githubusercontent.com/assets/3100220/21327961/34e136cc-c5f7-11e6-9de2-8c8b069a5c63.png">
So I had tried the change you committed and it resulted in this on the front-end. You can check it out on OO staging. I think the real fix might be to use static width and height (i.e. 200x200) images for images.

**Comment by redshiftzero** [comment]
Waaah. Okay assigning myself, will figure out why this isn't working in Chrome.

**Comment by redshiftzero** [comment]
Faces are no longer squished, but there is some extra whitespace. I'm gonna leave the frontend alone for now because fixing some dead space is low priority.
